### ISSUE TITLE
Add (function) demo for headless oauth

### ISSUE THREAD

**Issue by petermeissner** [r-lib/httr#323]
As far as I can see headless oauth is not supported in httr? 

**Would it be possible to include the possibility to provide all credentials: key, secret, token, token secret - in `oauth1.0_token()`?**

Poking around and reading and copying code from [httr](https://github.com/hadley/httr/blob/master/demo/oauth1-twitter.r#L1) as well as from [twitteR package](https://github.com/geoffjentry/twitteR/blob/master/R/oauth.R#L18) I came up with a not so nice but working demo:

``` r
library(httr)
options("httr_oauth_cache"=FALSE)

#1. Find OAuth settings for twitter:
#    https://dev.twitter.com/docs/auth/oauth
oauth_endpoints("twitter")

#2. Register an application at https://apps.twitter.com/
#    Make sure to set callback url to "http://127.0.0.1:1410"
#
#    Replace key and secret below
myapp <- oauth_app("twitter",
  key = "fookey",
  secret = "foosecret"
)

#3. Get OAuth credentials
access_token="footoken"
access_secret="footokensecret"

twitter_token <-
  Token1.0$new(
    endpoint      = NULL,
    params        = list(as_header = TRUE),
    app           = myapp,
    credentials   = list(
      oauth_token = access_token,
      oauth_token_secret = access_secret
    )
  )


#4. Use API
req <- GET("https://api.twitter.com/1.1/statuses/home_timeline.json",
  config(token = twitter_token))
stop_for_status(req)
content(req)
```

**Comment by hadley** [comment]
It's now ~2.5 years since you filed this issue (!!). Do you think it's still important given that most APIs are switching to OAuth2? (my sense is no, it's probably not that important any more)

**Comment by petermeissner** [comment]
Afterthought:

The general problem here is not about the version of Oauth used but that with the particular implementation of credentials handling one basically needs a computer with a monitor, a browser, and a mouse to get the authentication working. 

This means that with this implementation you cannot run e.g. Twitterbot on a remote machine (or one has to use the workaround described here). 

I am not sure if this problem exists for Oauth2 authentication as well or if Oauth2 is implemented differently.

**Comment by hadley** [comment]
OAuth 2 provides a bunch more techniques to deal with this issue, so it's definitely becoming less of a problem. We're going to totally reconsider the OAuth API in httr2 to make it much more flexible. At the time I wrote httr, I thought OAuth was an authentication system, but it's really a system for making authentication systems. That means there's a lot of variability from site to site, and the httr API is not a good fit for the problem.

I'm going to close this issue, but I'm confident that it will be easier to resolve once we have a new API in httr2 (coming later next year).

**Comment by petermeissner** [comment]
Pretty solid package for a first try 😉 All the best for the the reincarnation!

Sounds all good to me.
