### ISSUE TITLE
LinkedIn 

### ISSUE THREAD

**Issue by j450h1** [r-lib/httr#378]
oauth2-linkedin.r

Keep getting this message when I try to authenticate. 

Title: Bad Request

invalid redirect_uri. This value must match a URL registered with the API Key.

I have set Authorized Redirect URLs to:

http://localhost:1410/

Any tips?

**Comment by j450h1** [comment]
Wow. Looked like I resolved my own issue. Strangely enough when I add, http://localhost:1410 without the slash as another Authorized Redirect URL, everything works fine! However, if I have just http://localhost:1410/ by itself it doesn't work. So to be clear, I have both added.

**Comment by j450h1** [comment]
Spoke too soon:

Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400).

**Comment by hadley** [comment]
http://localhost:1410/ (with slash) works for me.
