### ISSUE TITLE
Rename length.path

### ISSUE THREAD

**Issue by nicolewhite** [r-lib/httr#395]
Hi! You have an [S3 method](https://github.com/hadley/httr/blob/master/NAMESPACE#L15) in your namespace [defined here](https://github.com/hadley/httr/blob/2b09b32a9acdb1ca40543ed05576516b1264c887/R/write-function.R#L89) that's overriding the `base::length` function when I assign the class 'path' to an object.

See:
- http://stackoverflow.com/questions/39185171/how-to-override-exported-function-from-r-package-listed-in-imports
- https://support.bioconductor.org/p/79059/
- https://github.com/nicolewhite/RNeo4j/issues/43

If it could be renamed / changed in some way, that would be great!

**Comment by pipemg** [comment]
I have the same problem and others in the community of bioconductor

**Comment by JackieMium** [comment]
same problem here. might be related to [this](https://support.bioconductor.org/p/79059/)
