### ISSUE TITLE
Offer to extend support of different HTTP responses

### ISSUE THREAD

**Issue by hrbrmstr** [r-lib/httr#396]
I'm building out https://gitlab.com/hrbrmstr/warc for a work project (giving gitlab a try as well so as to not put all the code eggs into the monolithic github basket) and right now it's designed to work with WARC `response`s (using `wget`'s WARC output for most of our short-term testing). I turn the object that gets built from a WARC `response` into something that `httr` can handle (it's classed as both a `warc_response` and `response` and the object structure mirrors - as closely as a WARC response can - a standard `httr` response). 

`httr`s mission is to do things like follow redirects and ultimately try to get to a nice HTTP `200` response with content (usually HTML, but as anyone who might be looking at this knows it handles much more than that).

In testing, there are some edge cases (mostly due to redirects or badly behaving sites) that leave some headers - like `Content-Type` - blank and also have content that is correct but causes `httr` some consternation.

Right now, I'm working around some of this, but I can work up the full list of issues if there's interest in having `httr` support a broader range of `response` objects (like 30x redirects, 404s, etc) and easier ways (besides munging curl handle options directly) to not follow redirects (etc). 

I would also be trying to add an `as_warc()` function to convert `httr` responses to WARC format (but the `response` object would need some additions to support that as well).

It's also completely doable to have all this be in some other (new) package or aligned solely with this forthcoming `warc` package (I have CRAN plans once it supports more WARC object types), but I wanted to see if folks would rather the more request-y changes go in here since this is now the gold standard package for making internet requests.

**Comment by hadley** [comment]
I'd say this is out of scope for httr, but is something that we'd love for httr2 (which probably won't happen until next year)
