### ISSUE TITLE
Multiple query parameters

### ISSUE THREAD

**Issue by dareid** [r-lib/httr#401]
I am trying to make a call like:

```
https://httpbin.org/get?test=1&test=2
```

I had assume this would be possible by calling:

```
GET("https://httpbin.org/get", query=list("test"=c(1,2)))
```

but this does not seem to be the case. Does httr support this?

**Comment by hadley** [comment]
```R
httr::GET("https://httpbin.org/get", query=list("test"=1, "test" = 2))
```

**Comment by dareid** [comment]
Thanks for pointing me in the right direction :+1:
