### ISSUE TITLE
Httr:content error version 1.2.1, readr 1.0.0

### ISSUE THREAD

**Issue by vblain** [r-lib/httr#402]
When calling httr:content I'm receiving the following error from readr::read_csv. Any recommendations to fix this?

 Error in readr::read_csv(x, locale = readr::locale(encoding = encoding),  : 
  unused arguments (check.names = FALSE, na.strings = "\N", colClasses = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA))

**Comment by hadley** [comment]
In general, it's better to not rely on auto parsing, and instead parse yourself.
