### ISSUE TITLE
Rough edges in modifying URLs

### ISSUE THREAD

**Issue by mbojan** [r-lib/httr#403]
I'm developing a wrapper around an API of a system instances of which can be behind different URLs. For example `http://somewhere.net/apiendpoint` or `http://apiendpoint.somewhere.net/` and so on. In other words the base URL may have a path component or may not. I use `modify_url` to construct requests to various parts of the API. I tried to walk around the replacement feature of `modify_url` (as in #185 ). Assuming I want to store the base URL in an environment variable or R option it is hard to modify it generically depending whether it does have a path component:

``` r
baseurl <- "http://somewhere.net/apiendpoint"

modify_url(baseurl, path="data", query=list(id=1))
#> [1] "http://somewhere.net/data?id=1"

# First parse the base URL and prepend the `path`
u <- parse_url(baseurl)
modify_url(u, path=c(u$path, "data"), query=list(id=1))
#> [1] "http://somewhere.net/apiendpoint/data?id=1"
```

so far so good, but:

``` r
baseurl <- "http://apiendpoint.somewhere.net/"

modify_url(baseurl, path="data", query=list(id=1))
#> [1] "http://apiendpoint.somewhere.net/data?id=1"

u <- parse_url(baseurl)
modify_url(u, path=c(u$path, "data"), query=list(id=1))
#> [1] "http://apiendpoint.somewhere.net//data?id=1"
u$path
#> [1] ""
```

path is an empty string so the result has two slashes...

or maybe there is better way to do it?

**Comment by hadley** [comment]
`parse_url()` doesn't parse the path into components, so you'll need to do it yourself. Something like this should suffice:

```R
baseurl <- "http://apiendpoint.somewhere.net/"

u <- parse_url(baseurl)
u$path <- strsplit(u$path, "/")[[1]]
u$path <- c(u$path, "data")
build_url(u)
```
