### ISSUE TITLE
Authentication in browser

### ISSUE THREAD

**Issue by cassiel74** [r-lib/httr#407]
I am working with rStrava which in turn uses httr for authentication on http://www.strava.com
I pushed all the stuff in a remote server hence no DE and connection with terminal.

Locally everything works fine, I run the script, the browser opens and auth process goes on but when I run the script from remote server the auth process never ends because of browser not opening.
Is there any workaround for this? Is it just a bug or what?

Regards

**Comment by hadley** [comment]
You can't use interactive auth on a server because you can't access the browser on that server. You'll need to use an alternative means of authentication, typically by saving the credentials that you generate locally.
