### ISSUE TITLE
Reddit oauth2 error in R Too Many Requests (RFC 6585) (HTTP 429). Failed to get an access token.

### ISSUE THREAD

**Issue by mikeyrocks11** [r-lib/httr#413]
Hello,

I am trying to get a oauth2 authorization for R studio, I have followed the API documentation as closely as I could for R. I also followed the `oauth2 reddit` Hadley had provided, though the code works, I am getting an issue when I am running the `oauth2.0_token` function. I run the code with the correct args and then takes me to my browser to ask authorization for request to connect with your reddit account 'Allow' or 'Decline' . Click allow and go back to R with this error message:

`Authentication complete.`
`Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope, :`
`Too Many Requests (RFC 6585) (HTTP 429). Failed to get an access token.`

help?

**Comment by hadley** [comment]
Fixed in #460
