### ISSUE TITLE
did not parse content of html5 document

### ISSUE THREAD

**Issue by NMarkgraf** [r-lib/httr#414]
I tried the current head code to get and parse information of a html5 document, but the content function could not parse anything correctly.

library(httr)
r <- GET("http://permanenzen.westspiel.de/default.aspx?casino=42&datum=29.11.2016", type = "text/html", verbose())
t <- content(r)
s <- str(t)

If you try it, you will always get an empty s. if you take a look at t there will be always a "{xml-document}" in the first line. 
Am I using it wrong, or is there a bug in the code?

**Comment by hadley** [comment]
That's just how xml/html documents print
