### ISSUE TITLE
httr and shiny server

### ISSUE THREAD

**Issue by glennmschultz** [r-lib/httr#416]
I have code to download from a website which works fine in R studio but does not work on R Studio  Server.  I have updated all packages on the shiny server still the program does not run.  I have traced the problem to the following....

    # handle preserves settings and cookies across multiple requests.  It is 
    # a foundation of all requests performed through httr.  
    h <- handle(
      "https://mbsdisclosure.fanniemae.com/PoolTalk/index.html")
  
    # Here the username and password are posted to the server.  Note that
    # user name and password are posted to .../login.json
    GET(handle = h)
    login <- POST(url = "https://mbsdisclosure.fanniemae.com/PoolTalk/login.json", 
                  body = list(username = username, 
                              password = password), 
                  encode = "form", handle = h)

GET(handle = h) times out however my understanding is handle is in memory so I am not sure why the problem occurs here but since the code works in RStudio and not R Studio Server I am assuming there is something with the way httr and shiny server interact

**Comment by hadley** [comment]
Are you sure the computer that shiny server is running on has access to the internet? I'd recommend checking with the server administrator.
