### ISSUE TITLE
"httpuv" library required for successful authorization

### ISSUE THREAD

**Issue by brezniczky** [r-lib/httr#418]
I am using httr 3.3 to access GitHub.

I followed the oauth2 github demo.
https://github.com/hadley/httr/blob/master/demo/oauth2-github.r

Appears when the in-browser authorization was to take place, after a successfully initiated request with correct oauth credentials, there's no interaction, I simply get an "401 Unaothorized (HTTP 401)." error message on the console.

This is so unless I install the httpuv package, afterwards everything works fine.

Maybe it is some missing package dependency for possibly specific cases (UPDATE: I am using Lubuntu with Google Chrome Version 55.0.2883.87 64-bit), or a miscommunicated error message? Googling a bit suggests occasionally there are others bumping into the same problem. (That was how I found out about what to do.)

**Comment by brezniczky** [comment]
(Sorry if it is a deprecated issue.)

**Comment by hadley** [comment]
There's already this code:

```R
  if (!use_oob && !is_installed("httpuv")) {
    message("httpuv not installed, defaulting to out-of-band authentication")
    use_oob <- TRUE
  }
```

So I'm not sure why you're not seeing this message. 

Anyway, I'll pull this out into a function and make some improvements.

**Comment by brezniczky** [comment]
Thank you for taking the time and looking into it!
