### ISSUE TITLE
Reading Content

### ISSUE THREAD

**Issue by msgoussi** [r-lib/httr#422]
Dear Mr. Hadely,
I have two difference urls and every 
url1<-"http://www.imf.org/external/np/fin/ert/GUI/Pages/Report.aspx?CU='AED','ATS','AUD','BEF','BHD','BND','BRL','BWP','CAD','CHF','CLP','CNY','COP','CYP','CZK','DEM','DKK','DZD','EEK','ESP','EUR','FIM','FRF','GBP','GRD','HUF','IDR','IEP','ILS','INR','IRR','ISK','ITL','JPY','KRW','KWD','KZT','LKR','LUF','LYD','MTL','MUR','MXN','MYR','NLG','NOK','NPR','NZD','OMR','PEN','PHP','PKR','PLN','PTE','QAR','RUB','SAR','SEK','SGD','SIT','SKK','THB','TND','TTD','USD','UYU','VEB','VEF','ZAR'&EX=REP&P=DateRange&Fr=635556672000000000&To=636203808000000000&CF=Compressed&CUF=Period&DS=Descending&DT=Blank"

url2<-"http://www.imf.org/external/np/fin/ert/GUI/Pages/Report.aspx?CU='AED','ATS','AUD','BEF','BHD','BND','BRL','BWP','CAD','CHF','CLP','CNY','COP','CYP','CZK','DEM','DKK','DZD','EEK','ESP','EUR','FIM','FRF','GBP','GRD','HUF','IDR','IEP','ILS','INR','IRR','ISK','ITL','JPY','KRW','KWD','KZT','LKR','LUF','LYD','MTL','MUR','MXN','MYR','NLG','NOK','NPR','NZD','OMR','PEN','PHP','PKR','PLN','PTE','QAR','RUB','SAR','SEK','SGD','SIT','SKK','THB','TND','TTD','USD','UYU','VEB','VEF','ZAR'&EX=REP&P=DateRange&Fr=633347424000000000&To=635555808000000000&CF=Compressed&CUF=Period&DS=Descending&DT=Blank"

if I use httr::GET(url1)
httr::content(httr::GET(url1),"text")
httr::content(httr::GET(url2),"text") 
it gives me the same content although url1 is different than url2, how can I solve this problem by deleting cookies.

**Comment by hadley** [comment]
You can manually set cookies with `set_cookies()` or manually construct a new handle for each request.
