### ISSUE TITLE
Resolving localhost in GET (SSH tunnel)

### ISSUE THREAD

**Issue by kevinykuo** [r-lib/httr#431]
Here's my setup:
- Azure VM running RStudio Server and Livy
- `spark_connect` via livy works in RStudio Server on the VM
- ssh tunnel binding ports 8998 and 8787 to corresponding ports on localhost

I'm able to browse to the "Operational Menu" via browser (`http://localhost:8998`) and `curl http://localhost:8998` in PowerShell works fine, but when I try `httr::GET("http://localhost:8998")` (and also `:8787`) I get a 404 along with some boilerplate message from corporate. Local machine is a running Windows 10 behind corporate proxy. I tried passing `use_proxy` with the appropriate settings but still no dice.

**Comment by hadley** [comment]
I don't quite understand what the problem is.

**Comment by kevinykuo** [comment]
Closing since it doesn't bother me for now, will reopen with reprex if needed.
