### ISSUE TITLE
OAuth 1.0 does not follow RFC 5849

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/httr#432]
httr package sends `oauth_callback` parameter in a request of token acquisition, which is not referred in [Section 2.3, RFC 5849](https://tools.ietf.org/html/rfc5849#section-2.3). This is because the current implementation of `init_oauth1.0()` reuses the function to build the OAuth 1.0 header. More precisely, [this function](https://github.com/hadley/httr/blob/1fc659856602f60ff75eb01903513244e3491ec2/R/oauth-init.R#L18-L21):
```r
  oauth_sig <- function(url, method, token = NULL, token_secret = NULL, private_key = NULL, ...) {
    oauth_header(oauth_signature(url, method, app, token, token_secret, private_key,
        other_params = c(list(...), oauth_callback = oauth_callback())))
  }
```

You know, this doesn't violate the RFC as it doesn't prohibit to include arbitrary additional parameters. However, sadly, there are some web APIs that considers it wrong... I had to re-implement the custom `oauth_init()` for the API: https://github.com/yutannihilation/hattnr/blob/c3ac12b0ea726eb202e6b865fe5204f2200fed63/R/oauth.R#L26-L55

Please consider providing a way to specify the different functions to build OAuth headers for the Resource Owner Authorization endpoint and for the Token Request endpoint separately.

Thanks!

**Comment by hadley** [comment]
I think this will probably have to wait for httr2 where we'll re-engineer the whole OAuth system to allow much finer control.
