### ISSUE TITLE
Keep all redirect URLs in the response object

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/httr#445]
This is not so important, it is just for the sake of completeness. `httr` does a pretty good job keeping the headers for all redirected requests in a redirect chain, but it does not actually keep the urls.

Maybe there could be an `urls` member if `response` objects, to keep them?

**Comment by hadley** [comment]
I think this is out of scope, but we should consider for httr2

**Comment by gaborcsardi** [comment]
Well, it is already keeping *all* the headers. So I guess it would make sense to keep the urls as well. I can probably send a small PR....
