### ISSUE TITLE
POST empty parameters

### ISSUE THREAD

**Issue by kongdd** [r-lib/httr#454]
When post empty parameters, some error encoded characters occur:

`library(httr)
x <- list(a = "", b = "")
p <- POST(
  "http://httpbin.org/post",
  body = x,
  verbose(), encode = "multipart"
) %>% content()

str(p$form)`

In the console, echo:
`-> POST /post HTTP/1.1
-> Host: httpbin.org
-> User-Agent: libcurl/7.53.1 r-curl/2.7 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Length: 234
-> Expect: 100-continue
-> Content-Type: multipart/form-data; boundary=------------------------63a63d36d5e2ab59
-> 
 --------------------------63a63d36d5e2ab59
 Content-Disposition: form-data; name="a"
 
 x梥
 
 --------------------------63a63d36d5e2ab59
 Content-Disposition: form-data; name="b"

 @7S	
 --------------------------63a63d36d5e2ab59--

<- HTTP/1.1 100 Continue
<- HTTP/1.1 200 OK
<- Connection: keep-alive
<- Server: meinheld/0.6.1
<- Date: Mon, 03 Jul 2017 14:43:56 GMT
<- Content-Type: application/json
<- Access-Control-Allow-Origin: *
<- Access-Control-Allow-Credentials: true
<- X-Powered-By: Flask
<- X-Processed-Time: 0.00165581703186
<- Content-Length: 590
<- Via: 1.1 vegur
<- 

**str(p$form)
List of 2
 $ a: chr "x<U+FFFD>s\n"
 $ b: chr "@7S\t"**`

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by kongdd** [comment]
Thanks very much. Jeroen has fixed this debug in [https://github.com/jeroen/curl/issues/103](curl package).
