### ISSUE TITLE
POST/PUT rounding numeric data

### ISSUE THREAD

**Issue by jdkleiner** [r-lib/httr#455]
Doesn't properly handle data of the type numeric when using POST/PUT functions 

When attempting to post or put a number with more than 4 digits after the decimal such as 0.00715 as type "numeric", the value gets rounded to a maximum number of characters, when setting as type "character" the full value is posted correctly without trimming. 

```
value <-  as.numeric(as.character(0.00715)) 
#This results in the value 0.0072 being posted/put

value <-  as.character(0.00715)
#This results in the value 0.00715 being posted/put

```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by jdkleiner** [comment]
For context, this issue involves setting a timeseries value attached to a drupal entity.

Below is example code using POST to set a numeric timeseries value, followed by a GET to confirm the value was rounded when using the previous POST function.

```
library(httr)

# Input value to be POSTed to drupal feature entity
value <- as.numeric(0.00715)

# Cross-site Request Forgery Protection (Token required for drupal POST and PUT operations)
csrf <- GET(url = "http://deq1.bse.vt.edu/d.bet/restws/session/token/", 
            authenticate("hidden_rest_username", "hidden_rest_password"))
token <- content(csrf)

# POST timeseries to drupal timeseries table
post_ts <- POST("http://deq1.bse.vt.edu/d.bet/dh_timeseries/", #POST timeseries to drupal timeseries table
                  add_headers(HTTP_X_CSRF_TOKEN = token),
                  body = list(
                    featureid = 65259, #drupal feature id 
                    varid = 1021, #drupal timeseries variable id 
                    entity_type = 'dh_feature', 
                    tsvalue = value, #drupal timeseries value
                    tstime = as.numeric(as.POSIXct(as.character("2017-01-01"),origin = "1970-01-01")) #drupal timeseries timestamp
                  ),
                  encode = "json")

# retrieve timeseries value created
get_ts <- GET("http://deq1.bse.vt.edu/d.bet/dh_timeseries.json", 
                  add_headers(HTTP_X_CSRF_TOKEN = token),
                  query = list(
                    featureid = 65259,
                    varid = 1021,
                    entity_type = 'dh_feature',
                    tstime = as.numeric(as.POSIXct(as.character("2017-01-01"),origin = "1970-01-01"))
                  ),
                  encode = "json")

get_ts <- content(get_ts)
print(get_ts$list[[1]]$tsvalue)
#> [1] "0.0072"
```

**Comment by hadley** [comment]
Can you please add `verbose()` to `POST()` and rerun?

**Comment by jdkleiner** [comment]
verbose() output: 

```
-> POST /d.bet/dh_timeseries/ HTTP/1.1
-> Host: deq1.bse.vt.edu
-> User-Agent: libcurl/7.51.0 r-curl/2.3 httr/1.2.1
-> Accept-Encoding: gzip, deflate
-> Cookie: hidden_cookie
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/json
-> HTTP_X_CSRF_TOKEN: hidden_token
-> Content-Length: 96
-> 
>> {"featureid":65259,"varid":1021,"entity_type":"dh_feature","tsvalue":0.0072,"tstime":1483246800}

<- HTTP/1.1 201 Created
<- via: SWG
<- Date: Tue, 25 Jul 2017 13:46:57 GMT
<- Server: Apache/2.4.18 (Ubuntu)
<- Expires: Sun, 19 Nov 1978 05:00:00 GMT
<- X-Cache: MISS from 
<- Content-Type: application/json
<- Cache-Control: no-cache, must-revalidate
<- Content-Length: 107
<- Proxy-Connection: Keep-Alive
<- X-Content-Type-Options: nosniff
<- 
```

**Comment by hadley** [comment]
This is due to the use of `jsonlite::toJSON()` which defaults to `digits = 4`.  I don't currently see an easy way to pass additional arguments to where the coercion happens, so I think the best approach is for you to convert to JSON yourself, so you can control the details of the translation.

**Comment by jdkleiner** [comment]
That actually makes a lot of sense, thank you for the quick response!

And for what it's worth, setting the value `as.character()` rather than `as.numeric()` retains all digits just fine as is.

**Comment by gdmcdonald** [comment]
My colleague fixed this issue by adding `options(digits = 10)` somewhere up the top of his code. Bit of an ugly hack but it made it work.
