### ISSUE TITLE
OAuth 1.0 fails to escape white space properly.

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/httr#469]
(This is a reprex for #441)

When the query string contains `+` character, the request fails if the query is directly included in the URL. On the other hand, it succeeds with `query` parameter.

```r
library(httr)

app <- oauth_app(
  "twitter",
  key = "xxxxxxxxx",
  secret = "xxxxxxxxxx"
)

twitter_token <- oauth1.0_token(oauth_endpoints("twitter"), app)

# OK
GET("https://api.twitter.com/1.1/search/tweets.json",
    query = list(q = "13+Reasons+Why"),
    config(token = twitter_token))
#> Response [https://api.twitter.com/1.1/search/tweets.json?q=13%2BReasons%2BWhy]
#>   Date: 2017-08-02 00:57
#>   Status: 200
#>   Content-Type: application/json;charset=utf-8
#>   Size: 150 kB

# Error
GET("https://api.twitter.com/1.1/search/tweets.json?q=13+Reasons+Why",
    config(token = twitter_token))
#> Response [https://api.twitter.com/1.1/search/tweets.json?q=13+Reasons+Why]
#>   Date: 2017-08-02 00:57
#>   Status: 401
#>   Content-Type: application/json; charset=utf-8
#>   Size: 64 B
```

I suspect something is wrong with the handling of `+`, which is a bit tricky. RFC 5849 says that the percent encoding used in OAuth 1.0 is:

> different from the encoding scheme used by the
   "application/x-www-form-urlencoded" content-type (for example, it
   encodes space characters as "%20" and not using the "+" character).

That said, I guess the query was wrong in this case. It seems that @Jibril2 did not intend to use `+` as plus character, but white space. In the example above, `query` parameter treats the string as it is, I mean, the plus character. So the code should be:

```r
GET("https://api.twitter.com/1.1/search/tweets.json",
    query = list(q = "13 Reasons Why"),
    config(token = twitter_token))

# This also fails:
# GET("https://api.twitter.com/1.1/search/tweets.json?q=13 Reasons Why",
#     config(token = twitter_token))
```

**Comment by jennybc** [comment]
Possible re-hashing of https://github.com/r-lib/httr/issues/335 and related PRs.

**Comment by yutannihilation** [comment]
@jennybc Thanks, will have a look!

**Comment by yutannihilation** [comment]
I found that it depends on whether `query` is specified whether `httr:::handle_url()` may parse and build the URL or not.

``` r
dummy_GET <- function(url = NULL, config = list(), ..., handle = NULL) {
  hu <- httr:::handle_url(handle, url, ...)
  hu$url
}

# If "q" is included in the URL directly, `url` is not parsed.
dummy_GET("https://api.twitter.com/1.1/search/tweets.json?q=13+Reasons+Why")
#> [1] "https://api.twitter.com/1.1/search/tweets.json?q=13+Reasons+Why"

# If "q" is specified as a `query` param, `url` is parsed.
dummy_GET("https://api.twitter.com/1.1/search/tweets.json",
          query = list(q = "13+Reasons+Why"))
#> [1] "https://api.twitter.com/1.1/search/tweets.json?q=13%2BReasons%2BWhy"

# Even if "q" is included in the URL, URL is parsed when `query` param is specified.
dummy_GET("https://api.twitter.com/1.1/search/tweets.json?q=13+Reasons+Why",
          query = list(test = "test"))
#> [1] "https://api.twitter.com/1.1/search/tweets.json?q=13%2BReasons%2BWhy&test=test"
```

**Comment by hadley** [comment]
I think the httr philosophy is that if you create the url yourself, we expect you to encode it correctly. However, if httr creates it for you, it should take care of the encoding. To me, that implies that the bug is your final example:

```
GET("https://api.twitter.com/1.1/search/tweets.json",
    query = list(q = "13 Reasons Why"),
    config(token = twitter_token))
```

Why are the spaces not getting correctly encoded?

**Comment by yutannihilation** [comment]
> Why are the spaces not getting correctly encoded?

Ah, sorry for confusing you... This example is fine and the spaces are encoded properly (whereas the url `https://api.twitter.com/1.1/search/tweets.json?q=13 Reasons Why`, which I create by myself, fails):

```r
GET("https://api.twitter.com/1.1/search/tweets.json",
    query = list(q = "13 Reasons Why"),
    config(token = twitter_token))
#> Response [https://api.twitter.com/1.1/search/tweets.json?q=13%20Reasons%20Why]
#>   Date: 2017-08-02 13:07
#>   Status: 200
#>   Content-Type: application/json;charset=utf-8
#>   Size: 73.1 kB
```

**Comment by hadley** [comment]
I'm happy with the current philosophy. We may reconsider for httr2.
