### ISSUE TITLE
httr 1.3.0 does not cache to .httr-oauth file nor use it

### ISSUE THREAD

**Issue by tjpalanca** [r-lib/httr#475]
I'm using `gmailr` to send mail via the gmail API. As far as I know, OAuth 2.0 is handled via `httr`.

When I upgraded to httr 1.3.0 it seemed that the cache file `.httr-oauth` was no longer saving, nor was it used when it was in the working directory. I downgrade to 1.2.1 and everything is fine.

Unfortunately I can't find a way to make it a reproducible example but this is what i do:

```{r}
# SETUP: There is already an .httr-oauth file in the working directory

# Install 1.2.1
library(devtools)
install_version("httr", "1.2.1")

library(gmailr)
library(httr)
options(httr_oauth_cache = TRUE, httr_oob_default = TRUE)
gmail_auth()

# DO: Restart R Session

# Install 1.3.0
library(devtools)
install.packages("httr")

library(gmailr)
library(httr)
options(httr_oauth_cache = TRUE, httr_oob_default = TRUE)
gmail_auth()
```

When you install 1.3.0, it again requests for notification. When you install 1.2.1 again, it just used the cache file.

I haven't gotten to looking at diffs to see what changed, but putting this up here in case other people are experiencing an issue.

**Comment by naltmann** [comment]
I also experienced this problem. Downgrading to 1.2.0 fixed it immediately, and everything worked as expected.

**Comment by jennybc** [comment]
I believe I found the change that had this effect ☝️. At least my git bisect exercise suggests so and it also makes sense.

The dev version just prior seems ok wrt @tjpalanca's reprex:

```
install_github("r-lib/httr@99b256c0a12b91f9d6e7580d5f6b70703970bf18")
```

**Comment by hadley** [comment]
I'll do a fix and release a patch version tomorrow

**Comment by hadley** [comment]
Just fixed - I'd really appreciate it if someone else would test it before I re-release

**Comment by jennybc** [comment]
It looks like everything is back in business to me! 👍

**Comment by hadley** [comment]
Thanks! I'll submit shortly
