### ISSUE TITLE
Cannot read token from alleged .rds file

### ISSUE THREAD

**Issue by ErezLo** [r-lib/httr#480]
Hey

I hope I am in the right place :)

I am trying to scedule a script using taskscheduleR and googleAnalyticsR by Mark Edmondson.

I have this script which is working manually

```
library(tidyverse)
library(googleAnalyticsR)

googleAuthR::gar_auth(Sys.getenv("GA_AUTH_FILE"))
desktop_id <- 1234
as.Date(this_year_start <- "2017-07-01")
as.Date(this_year_end <- "2017-07-31")
as.Date(last_year_start <- "2016-07-01")
as.Date(last_year_end <- "2016-07-31")

## DESKTOP REPORTING

adesktop_hostnames <- google_analytics(desktop_id,start=this_year_start, end=this_year_end,
                                       metrics = c("sessions"),
                                       dimensions = c("hostname"),
                                       max_results = 999999)
```

I have an `.Renviron` file with this 
`GA_AUTH_FILE = "/Users/Erez/Documents/.httr-oauth"
`
when i check the path using `file.exists(Sys.getenv("GA_AUTH_FILE"))` it evaluates to true.
I tried deleting it and authorized again.
I reinstalled R and Rstudio from scratch without luck.

when I am running the scripts manually they are working perfectly.
When they are scheduled for some reason the log file returns 

```
Error in read_cache_token(token_path = token) : 
  Cannot read token from alleged .rds file:
Calls: <Anonymous> -> read_cache_token
Execution halted
```

If I understand the flow correctly then the RDS is inside the `.httr-oauth`

I've read this entire article and everything is in the place, the script and the `.httr-oauth` file.

_https://cran.r-project.org/web/packages/googlesheets/vignettes/managing-auth-tokens.html_

Would love to hear your input if I am missing something.

Thank you very much for your time

**Comment by jennybc** [comment]
It sounds like you are mixing two workflows for making a cached token available to a script.

`.httr-oauth` is httr's destination for automatically cached tokens and it has the potential to store multiple tokens. They are in a key-value store where the key is formed by the combination of endpoint, app, and scopes.

In googlesheets and, I'm guessing, googleAuthR, we offer an alternative workflow where we save exactly one token to a descriptively named `.rds` file. The vignette you link to has code for storing exactly one token in this way:

```
library(googlesheets)
token <- gs_auth(cache = FALSE)
saveRDS(token, file = "googlesheets_token.rds")
```

It sounds like you are placing an `.httr-oauth` cache file somewhere (option 1) then are providing it to a function that expects a single token stored in an `.rds` file (option 2). I.e. you're mixing the two.

**Comment by ErezLo** [comment]
Hi Jenny

Thank you for your time.

So i need to save my GA auth (client_id, secret_key) in and RDS file and then use it to authenticate within the script ?

Are you familiar with a way to create this token in googleAnalyticsR or googleAuthR ?
My guess is I cant use the script your provided because it will save me the auth for google sheets.

Am I correct ?

Thanks

**Comment by jennybc** [comment]
My knowledge of googleAnalyticsR or googleAuthR isn't detailed enough to say exactly how you're meant to create the auth file. But I recommend you close this issue and  re-open it on one of those packages/repos.

**Comment by ErezLo** [comment]
Thank you

Appreciate your help
