### ISSUE TITLE
oauth2.0_access_token : "Bad Request (HTTP 400). Failed to get an access token" using Yahoo API Oauth2.0

### ISSUE THREAD

**Issue by infinitetrial** [r-lib/httr#483]
I had to switch my code to Yahoo Oauth 2.0 due to issues with Yahoo API Oauth 1.0 recently (problem on Yahoo's end, getting Internal Server Error).

I am testing the functions manually first and running into the following error when using _oauth2.0_token_:
```
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token.
```

Aside from this error, I encountered several issues leading to this which are explained below.

**Steps to reproduce error:**

1. Used oauth_endpoint vs. oauth_endpoints("yahoo")
- when using oauth_endpoints("yahoo"), I do not get the authorization code in the request page

oauth_endpoint **(test)** value:
```
<oauth_endpoint>
 authorize: https://api.login.yahoo.com/oauth2/request_auth
 access:    https://api.login.yahoo.com/oauth2/get_token 
```
2. When adding **use_oob = TRUE**, redirect_uri becomes "urn:ietf:wg:oauth:2.0:oob" and Yahoo gives me an error to check my redirect_uri. Omitting use_oob, however does not prompt me to enter the authorization code. I included **use_oob = TRUE** and get the authorization code by manually correcting the redirect_uri on my browser.
3. Request that returns "Bad Request (400)":
```
> oauth2.0_token(test,oauth_app("FF",key=cKey,secret=cSecret,redirect_uri="oob"),use_oob=TRUE,scope="openid,fspt-r")
Enter authorization code: 2gbh2ua
Error in oauth2.0_access_token(endpoint, app, code = code, user_params = user_params,  : 
  Bad Request (HTTP 400). Failed to get an access token.
```
4. Taking the authorization code and manually executing **oauth2.0_access_token** gives me the token_id and other responses
`oauth2.0_access_token(test,oauth_app("FF",key=cKey,secret=cSecret,redirect_uri="oob"),code="2gbh2ua")`

**Comment by infinitetrial** [comment]
I just realized also that using the token I got from #4 gives me an error:
```
GET(paste0(leagueURL,"/settings"),config(token=yahoo_token))
Error in request_prepare(req) : attempt to apply non-function
```
This code used to work with oauth 1.0 token. The token format I get on 2.0 is like the $credentials portion of 1.0, so I am not sure if that is the problem.

**R version 3.3.3
httr 1.3.1
httpuv 1.3.5**

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by infinitetrial** [comment]
This was a personal project a year ago and unfortunately have completely forgotten about it. I’ll re-open if it’s still a problem once I revisit and provide a reprex. Thanks.
