### ISSUE TITLE
transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by giuseppec** [r-lib/httr#487]
I can't download this file here using `GET`: https://www.openml.org//api_splits/get/146542/Task_146542_splits.arff (maybe because it is too big?)

```r
GET("https://www.openml.org//api_splits/get/146542/Task_146542_splits.arff",
  progress(), timeout(3600))
```

After 100 - 200 MB I get the error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  transfer closed with outstanding read data remainingz
```

Looks like a problem with `curl` but maybe there is an option in `httr` that still allows me to download this file? 
Downloading the file with `download.file` seems to work. 
Issue comes from https://github.com/openml/openml-r/issues/392

**Comment by hadley** [comment]
This works for me. Do you still see the problem with latest curl?

**Comment by hadley** [comment]
``` r
library(httr)
x <- GET("https://www.openml.org//api_splits/get/146542/Task_146542_splits.arff")
```

<sup>Created on 2018-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
