### ISSUE TITLE
Issue with NTLM authentication  (after curl 3.0 )

### ISSUE THREAD

**Issue by maalsol** [r-lib/httr#488]
The following code works with curl 2.8.1

 ```
httr::set_config(config(ssl_verifypeer = 0L))
 response <- GET(requestURL, authenticate(":", ":", "ntlm"))
```

After the recent update to curl 3.0 I get the following error: 

"Error in curl::curl_fetch_memory(url, handle = handle) : 
  schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid"

The certificate is self signed, but it is trusted (checked with IE).
Any ideas?

**Comment by hadley** [comment]
No, sorry 😞 

For this sort of problem, you're probably better off filing issues with curl, since it's a lower-level problem.
