### ISSUE TITLE
oauth1.0_token or oauth2.0_token for vimeo?

### ISSUE THREAD

**Issue by braggbear** [r-lib/httr#491]
In the vimeo exampl, oauth1.0_token is used but I have read elsewhere that we should be using oauth2.0_token.  Should we use 2.0, not 1.0?  If so, could you update the vimeo example to ensure I have it right?  Thank you!!!

**Comment by smithjd** [comment]
The oauth 1.0 access point no longer works, so  oauth2.0 is much needed!  -- Please!

**Comment by smithjd** [comment]
With a few caveats, here is a work-around, using the [reticulate](https://github.com/rstudio/reticulate) package and examples [here](https://github.com/vimeo/vimeo.py):

```
library(reticulate)

# load python modules previously installed with pim:
os <- import("os")
sys <- import("sys")
vimeo <- import("vimeo")
json <- import("json")

v <- vimeo$VimeoClient(
  token = Sys.getenv("vimeo_api_access_token"),
  key = Sys.getenv("vimeo_api_key"),
  secret = Sys.getenv("vimeo_api_secret")
)

album <- v$get("/me/albums?per_page=100&fields=modified_time,name,duration,link,created_time")
album_json <- album$json()
```

Caveats:
- download Python modules vimeo and json
- obtain token, key, and secret [from vimeo](https://developer.vimeo.com/api/start)
- album_json is an R list that you can parse using R's various JSON methods.
