### ISSUE TITLE
Yahoo Fantasy sub-resource GET function call, semicolon in URI

### ISSUE THREAD

**Issue by bradyte** [r-lib/httr#492]
When querying the Yahoo Fantasy API, you can add additional parameters to access a sub-resource of the information. However, you use a semi-colon in the url to indicate the sub-resource:

https://developer.yahoo.com/fantasysports/guide/league-resource.html
`/fantasy/v2/league/{league_key}/scoreboard;week={week}`

This would indicate the scoreboard of a week other than the current one.

So one example I have been trying to make work is the following URI:

`https://fantasysports.yahooapis.com/fantasy/v2/teams;team_keys=371.l.470610.t.1/roster;week=1`

This would grab the roster of my team from week 1, however, it returns the following error:

> No encoding supplied: defaulting to UTF-8.
Error: XML content does not seem to be XML: '{"error":{"lang":"en-US","description":"Please provide valid credentials. OAuth oauth_problem=\"signature_invalid\", realm=\"yahooapis.com\""}}'

I have attached the example R code. When I do not use a semicolon in the URI, I can get the information with no issue.

I tried to replicate the issue using another language, Python, but I get all of the data with no issue. I have attached the Python code.

I believe the HTTR GET function does not like having the semicolon in the URI.
[Archive.zip](https://github.com/r-lib/httr/files/1418227/Archive.zip)

**Comment by jennybc** [comment]
Have you tried URL encoding the semi-colon containing URL with `URLencode()` before you give it to `httr::GET()`?

**Comment by bradyte** [comment]
Hello Jenny, I tried that with both the HTTR library and the urltools library but it did not work.

**Comment by cderv** [comment]
your error message states a credential issue 

> "Please provide valid credentials. OAuth oauth_problem="signature_invalid"

Are you sure the oauth workflow is ok ? Do not have a yahoo account myself to try. 
It seems you are using oauth2 mechanism in python but using oauth1 in R - not the same normally.
Have you tried a oauth2 workflow with `httr` ?

I would look into that before looking in the semi-colon encoding. This should not be a problem.
