### ISSUE TITLE
support for OAuth2 in Yahoo API

### ISSUE THREAD

**Issue by ctrombley** [r-lib/httr#493]
I was recently able to complete a successful auth flow against Yahoo's OAuth2 API with httr, but only after a few small changes:

1. The OOB flow [expects a request_uri value of `oob`](https://developer.yahoo.com/oauth2/guide/flows_authcode/#step-2-get-an-authorization-url-and-authorize-access) rather than [`urn:ietf:wg:oauth:2.0:oob`](https://github.com/r-lib/httr/blob/7150e8edd334d019788ee2d50ad831b48b9c6df0/R/oauth-init.R#L85).
1. The base url for Yahoo's OAuth2 endpoints had to be changed from [`https://api.login.yahoo.com/oauth/v2`](https://github.com/r-lib/httr/blob/master/R/oauth-endpoint.r#L89) to   [`https://api.login.yahoo.com/oauth2`](https://developer.yahoo.com/oauth2/guide/flows_authcode/#step-2-get-an-authorization-url-and-authorize-access).

Is there any desire to add either of these changes into the package?  I can take a stab at a PR if so.  For the first issue, it would be simple to add an override for the OOB string, with the option scoped either globally or to the app.  For the second, the existing endpoint could be updated or separate endpoints could be provided for OAuth1 and OAuth2.

Thoughts?

**Comment by Tectra** [comment]
@ctrombley would you be willing to sure your code? been struggling with getting oauth2 working.

**Comment by ctrombley** [comment]
@Tectra sure thing.  Keep in mind I am running an OOB OAuth flow, so I have provisioned a Desktop application in Yahoo.  Here's a gist:

https://gist.github.com/ctrombley/296c2d9eb2738642b953debfc7404b12

It requires my httr fork available here:
https://github.com/ctrombley/httr

Also worth noting that I am creating my own `oauth_app` rather than using `oauth_endpoints("yahoo")`. Here's the commit in my fork that allows overriding the `redirect_url` at the app level:
https://github.com/ctrombley/httr/commit/86b409d5036cf143b113290c2faf165a4aefd099

**Comment by hadley** [comment]
@ctrombley are you still interested in doing a PR? I'm happy to implement myself, but if you'd like to take a shot I'd be happy to review your code. Please let me know either way.

If so, the main challenge is figuring out how to specify the oob value. For now, since we'll reconsider this entire API in httr2, I'd recommend adding a new parameter, `oob_value`

**Comment by hadley** [comment]
(And also needs an update of the demo)

**Comment by ctrombley** [comment]
@hadley sure!  I'm throwing something together now.
