### ISSUE TITLE
curl::curl_fetch_memory timeout

### ISSUE THREAD

**Issue by alex-hioperator** [r-lib/httr#501]
Hi there,

I'm doing a rather long POST--I expect it will take a few minutes to return.

I tried to set the timeout using timeout(900), but it returns an error after about 10 seconds.

> Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Operation timed out after 10003 milliseconds with 0 out of 0 bytes received

If I set the timeout to below 10 seconds, then it times out earlier. So I suspect that the timeout is coming from a max set in curl? I can't seem to figure out how to update that setting to get a longer running post going.

**Comment by skyhias** [comment]
Hello, 

same observation for me. 

Also setting timeout to 0 does not work, this delivers:

> Error: Timeout cannot be less than 1 ms

I would have expected this to deactivate timeout (--> https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT_MS.html)

Is there any solution to have longer timeouts than 10s?

Thanks and best regards

**Comment by hadley** [comment]
The default is no timeout so you shouldn't need to set anything. Is it possible to make a reprex so I can test locally?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
