### ISSUE TITLE
can't get 'upload_file' in POST to work with Amazon WS S3 uploads

### ISSUE THREAD

**Issue by wsphd** [r-lib/httr#502]
An upload in Amazon Web Services S3 storage is often a two-step process (I'll speculate that's to mitigate against DOS attacks...).  The initial API request is a simple POST to a host application with, say, a filename, and perhaps a filesize to check for quota.  The response parameters (a "signed credential") from this POST are then used--verbatim--in a second POST with the addition of a "file" parameter at the end of the body.  For text files, a "file" parameter can simply be added manually and loaded with, say, a readr::read_file to populate the value.  But upload_file is needed for non-text files.  Upload_file generates two parameters, with the first one being the file.  But Amazon balks since the file *isn't* at the final parameter (argh!).

Here is an example of a workflow using the Canvas Learning Management System:

https://canvas.instructure.com/doc/api/file.file_uploads.html

Has anyone gotten httr::POST() with upload_file to work reliably with Amazon WS?  Is there any way to force httr to put the filename (and use the word "file" as the parameter) as the *last* parameter in a body?  Is there a way to upload a non-text file without using the POST upload_file option.

I suppose I could might try a workaround either with RCurl or hand-roll a specific CURL command line string and run it with base::system2(), but httr seems far more elegant (and works, by the way, in dozens of other scripts with many host APIs.  In fact, I find httr more useful and intuitive than either Python Requests or requests.jl in Julia (I suppose I could move Amazon file uploading to either of those too)

**Comment by hadley** [comment]
I'd recommend asking in http://community.rstudio.com/; I don't have any particularly useful thoughts.
