### ISSUE TITLE
SSL Connection relies on pfx (p12)

### ISSUE THREAD

**Issue by kokomoo** [r-lib/httr#506]
I'm quite addictive to httr now.
Here is my request

> `response = POST(url ="https://markets.midwestiso.org/darteor/xml/query",`
`content_type_xml(),
accept_xml(),
body = as.character(xml.body))`

xml.body is a soap message with query information.

I'm working on Windows OS.
This request would work if I imported the personal certificate (some pfx/p12 file) into the browser.
If i removed it, it would have the error.
> schannel:  failed to receive handshake, SSL/TLS connection failed.

My goal is to run it independently from OS.
I have tried bringing in config list with params cainfo, sslcert, sslkey, somehow it's still showing the 
same error.

> `response = POST(url ="https://markets.midwestiso.org/darteor/xml/query",`
`content_type_xml(),
accept_xml(),
config = config(cainfo = ca.file, sslcert = sslcert.file, sslkey = sslkey.file),
body = as.character(xml.body))`

ca.file, sslcert.file, sslkey.file are the file paths on my local drive, all pem files.
I used openssl package, read_p12() to read my pfx key and write_pem() to write ca, cert and key separately into 3 pems.

**Comment by hadley** [comment]
Unfortunately I can't help without a reprex, and it's going to be extremely difficult for you to create one. I'd recommend debugging by using `verbose()` and making sure that the SSL handshake is proceeding as expected; also double check that all the paths are correct and exist.
