### ISSUE TITLE
Capture a refresh token

### ISSUE THREAD

**Issue by moloscripts** [r-lib/httr#509]
I've generated a token using curl + curl converter but has a key-value pair. access token & a refresh token. How do I capture or 'store' a refresh token  using httr? This is my code. 
`reqq <- httr::VERB(
  verb = "GET",
  url = "url",
  httr::add_headers(
    Accept = "application/vnd.v2+json",
    `User-Agent` = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:58.0) Gecko/20100101 Firefox/58.0",
    `Authorization ` = "Bearer {access token}"
  )
)`

**Comment by cderv** [comment]
Note sure if this is exactly what you are looking for but FWIW, did you look into the [Managing Sevret](http://httr.r-lib.org/articles/secrets.html) vignette ? 
Moreover, `httr` has a caching mechanism for Tokens that helps you deal with storing token. Did you try that ?  (see [authentification functions](http://httr.r-lib.org/reference/index.html#section-authentication) or [token class](http://httr.r-lib.org/reference/Token-class.html))

**Comment by wastani** [comment]
@cderv tbh, not yet. I'll have a look
