### ISSUE TITLE
Can't replicate Facebook demo. FB requiring HTTPS

### ISSUE THREAD

**Issue by dcldmartin** [r-lib/httr#510]
I strongly suspect the reason I'm getting a bad request error from the Facebook API when trying to replicate results from the Facebook demo for requesting a token via OAuth2.0 is that they have changed their policy about allowing redirects not over HTTPS. So additional configuration may be required for this to work properly.

Per [Facebook's docs](https://developers.facebook.com/docs/facebook-login/security), the toggle for 'Enforce HTTPS' that could previously be turned off for apps has been disabled, so OAuth redirects must apparently come with a TLS certificate.

When executing the demo code, an error appears during authentication with Facebook in the browser: "Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://" and R shows a Bad Request error.

**Comment by braunm** [comment]
I have come across the same problem, but it is not clear what the recommended solution is.  Is installing a certificate on my computer sufficient, or is there some additional httr configuration that would be necessary?

**Comment by kelceywilson** [comment]
Same problem here. Not sure why this and https://github.com/daroczig/fbRads/issues/85 was closed with no solution...

**Comment by Gaut9a8m** [comment]
Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. 

please help with this problem

**Comment by andrex8** [comment]
same problem here, using Ionic 3 
insecure login blocked

**Comment by diegorochawebdg** [comment]
same problem, using Ionic 3
any suggestions?

**Comment by ryancha1205** [comment]
Is anyone can help us?

**Comment by schwarzcrepsley** [comment]
same here even when using https on dev environment without a valid cert.
unclear whether self-signed certs are acceptable, or do i have to pay some CA for one

**Comment by sachinbonzer** [comment]
The method FB.login will soon stop working when called from http pages. Please update your site to use https for Facebook Login.

please help with this problem

**Comment by hadley** [comment]
More discussion at https://community.rstudio.com/t/fboauth-integration-with-r-and-facebook/8536/4

**Comment by dsacramone** [comment]
IS there any real resolution with this?
