### ISSUE TITLE
Incompatibility of GET from FTP with openxlsx formatting 

### ISSUE THREAD

**Issue by skirmer** [r-lib/httr#514]
This may be too niche of an issue to be worth addressing, but I have a very idiosyncratic bug I've noticed.
If I create an xlsx file (`openxlsx::write.xlsx`) and post it to a secure FTP location (I'm using `RCurl::ftpUpload` for this), I am able to download it back from that FTP location with `httr::GET` no problem. 

However, if I change the xlsx in my working env from a flat file to a workbook (`openxlsx::loadWorkbook`) in order to make formatting adjustments to that xlsx (`openxlsx::setColWidths` and the like), and then save using `openxlsx::saveWorkbook`, I can still post it with the `RCurl::ftpUpload`, but I can no longer download it using `httr::GET`. The file is still `nameoffile.xlsx`, but the contents now contain formatting as well as the cell values. 

The specific GET statement I am using is this (some names changed for security reasons)
`filename <- httr::GET(url = "ftps://ftp.site.com/folder/nameoffile.xlsx"
                            , httr::authenticate(ftp_username, ftp_password)
                            , httr::write_disk("/home/temp_nameoffile.xlsx", overwrite=TRUE))`
and the error is:
`Error in curl::curl_fetch_disk(url, x$path, handle = handle) : Given file does not exist`

I have debugged the local `write_disk` side of things thoroughly, and have pinned down the issue to being the xlsx file's new formatting elements. The login to the FTP is working fine. Somehow, the `httr::GET` is not able to recognize the file's presence given the new formatting inside it. Other .xlsx files in the same FTP folder without these formatting changes download beautifully with `httr::GET`.

Any tips on how to resolve this would be very welcome! The formatting is necessary for business purposes, unfortunately, as is the xlsx file format. I have tried an approach using the package `xlsx` instead and the same issue is created, so I am hoping that perhaps the `httr` side might have a solution.

Edit: My suggestion for attempting to reproduce the bug:
I think it would work in another FTP location, so you could reproduce it anywhere that GET can find an .xlsx file. Save one with write.xlsx and save one with saveWorkbook, and I theorize that the latter won't be retrievable.

**Comment by hadley** [comment]
httr is only designed to support http/https, so unfortunately it's only luck that ftp works at all. I'd recommend using the lower-level curl package instead.
