### ISSUE TITLE
oauth1.0_token() Waiting for authentication in browser... Press Esc/Ctrl + C to abort

### ISSUE THREAD

**Issue by jthomp1818** [r-lib/httr#519]
Hello, I am experiencing a problem with the oauth1.0_token function. 

Everything seems to work just fine until it comes down to r receiving the browser authentication. Please see code used and message below:

```
# Designate URLs & Keys
upwork_url <- "https://www.upwork.com"
key <- "app_key"
secret <- "app_secret"
request <- paste0(upwork_url, "/api/auth/v1/oauth/token/request")
authorize <- paste0(upwork_url, "/services/api/auth")
access <- paste0(upwork_url, "/api/auth/v1/oauth/token/access")
callback <- "http://127.0.0.1:1410"

# Request Token
upwork_app <- oauth_app(appname = 'upwork', key = key, secret = secret, redirect_uri = callback)  
upwork_endpoints <- oauth_endpoint(request = request, authorize = authorize, access = access)
token <- oauth1.0_token(endpoint = upwork_endpoints, app = upwork_app)
```

When I run the above code, I get an Upwork webpage pop-up asking my Upwork account to lend the desired authorizations to the app and the below message in the r console:

```
# Message in console
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```

When I click the authorization button in the browser I get an oauth_verifier code (in the browser), but nothing happens in r. I never get the token or the token_secret. The r console just keeps running and showing the above message.

I saw a similar issue for the twitter API (#195). But it seems adding the callback URL took care of their problems. I've tried with and without the callback URL and no luck.

Any insights or help would be appreciated! Thank you!

**Comment by mkearney** [comment]
Just figured this out with Twitter's API, but I think it applies here as well: `httr::oauth1.0_token()` hardwires in "localhost" into the callback URL. If there are strict requirements for the callback URL (Twitter just started whitelisting them), then authorization will fail. You can see my fix to rtweet here https://github.com/mkearney/rtweet/commit/eb9b4008f751b3fcfad3170d51e6491963ce325a

**Comment by hadley** [comment]
Given that upwork appears to now support OAuth 2.0, I'd recommend using that instead.
