### ISSUE TITLE
httr::content fails with when I try to pass `locale` to the parsing function (read_csv) 

### ISSUE THREAD

**Issue by jlegewie** [r-lib/httr#520]
`httr::content` fails with when I try to pass `locale` to the parsing function `read_csv`. I think the reason is that `httr::content` calls `read_csv` with `readr::locale(encoding = encoding)` and that makes it impossible for the user to pass on their own locale settings. For example, in the code below I want to set the timezone to "EST". I don't have public API right now for a fully reproducible example. I will try to add one down the line but I hope that the problem is pretty clear.

```
httr::content(resp, locale = locale(tz = "EST"))
# Error in readr::read_csv(x, locale = readr::locale(encoding = encoding),  : 
#  formal argument "locale" matched by multiple actual arguments
```

**Comment by cderv** [comment]
> that makes it impossible for the user to pass on their own locale settings.

You may already know that but you can parsed the resulting content yourself to customise as you wish. 

As explains in the documentation
> as = "parsed" is provided as a convenience only: if the type you are trying to parse is not available, use as = "text" and parse yourself.

You can also use raw vector.

So you can do something like 
```r
httr::content(resp, as = "raw") %>% readr::read_csv(locale = yourcustomlocale())
```

FWIW, hopes it can helps.
