### ISSUE TITLE
Should check permission before overwriting

### ISSUE THREAD

**Issue by dkulp2** [r-lib/httr#521]
https://github.com/r-lib/httr/blob/381858b8f7de93bcce77b793d1f453a21dfdc77a/R/oauth-cache.R#L73

If the directory or file (e.g. .gitignore) is write protected, then currently `writeLines` fails. Instead, httr should probably try to write, but quietly continue if it cannot since this is just a convenience feature to avoid polluting a repo.

**Comment by jennybc** [comment]
@Hadley you may have misunderstood this? The write in question does not involve the token cache. This line is in the utility used to add lines to gitignore and Rbuildignore.

**Comment by hadley** [comment]
Ooooh oops
