### ISSUE TITLE
Need to use http://localhost:1410/ as redirect URI should be in comments of Reddit oauth demo

### ISSUE THREAD

**Issue by cstawitz** [r-lib/httr#525]
The Reddit OAuth demo doesn't work unless the redirect uri on the reddit app preferences page is set to exactly "http://localhost:1410/". As in lines 8-9 of the LinkedIn demo (below), this could also be specified in the comments of the Reddit demo:

`#    Make sure to register http://localhost:1410/ as the "redirect uri".`
`#    (the trailing slash is important!)`

**Comment by KasperSkytte** [comment]
Oh thank you! This has been bothering me for long with `rdrop2` and making Apps on dropbox. Entering this as redirect URI enabled me to authenticate and avoid access to my whole dropbox!
