### ISSUE TITLE
curl options

### ISSUE THREAD

**Issue by picousse** [r-lib/httr#535]
Hi,

> s_fetch_advanced <- function(query_object, sortby = NA, startrow = NA, endrow =NA, table="Content", config =ppR:::config()){
>  q_object = ppR:::s_complete_search(query_object, sortby = sortby, startrow = startrow, endrow = endrow)
> ha = ppR:::handle_creator(config$aa$username, config$aa$password) #basic handler setup
> **curl::handle_setopt(ha, postfields = q_object)** # enter the query
> query = sprintf('http://xxxx/xxxx/rest/%s/advanced', table)
> req <- jsonlite::fromJSON(curl::curl(query, handle = ha)) %>% as.data.frame # do the fetch, convert to JSON, convert to dataframe to work with
> return(req$entities.columns)
> }
> handle_creator <- function(username, password){
  >  h <- curl::new_handle() # setup the connection handler for SLims
   > curl::handle_setheaders(h, "Content-Type" = "application/json")
   > curl::handle_setopt(h, customrequest = "GET")
   > curl::handle_setopt(h, userpwd = paste(username, ":", password, sep=""))
   > return(h)
>}

Works more or less (although I get double hits on the server). But at least I get the correct answer. I wanted to change this to httr:

>   q_object = ppR:::s_complete_search(query_object, sortby = sortby, startrow = startrow, endrow = endrow)
>  query_base = sprintf('http://xxxxxxx/rest/rest/%s/advanced', table) # build the simple query
>   fetch <- GET(url = query_base, **config =list('postfields' = q_object)**,      authenticate(config$aa$username, config$aa$password))
>   status_code(fetch)

But this fails.
The original example I got form the api was:

> curl -u user:password -X GET -H 'Content-Type: application/json' \
	**-d q_object'** \
	http://zz.customer.com/zz/rest/ContentType/advanced

So I got it to work using curl, with the postfields part. However when I add_headers or use the config=list() to the get function, nothing seems to work.
What am doing wrong?

**Comment by cderv** [comment]
> curl -u user:password -X GET -H 'Content-Type: application/json'
-d q_object'
http://zz.customer.com/zz/rest/ContentType/advanced

From this, it seems that you have to make a POST request. 
try 
```r
library(httr)
res <- POST(query, 
    # pass your query in the body of the POST. 
    body = query, 
    # add header 'Content-Type: application/json'
    content_type_json(), 
    # add basic auth header
    authenticate(config_ib$slims$username, config_ib$slims$password, type="basic")
status_code(res)
```` 
As you did not provide a reprex, I can't try the code so this is a guess based on what you said work. 
`query` is not known to me. I assume it is a json string. Can you confirmed ? If not the content type should be adapted and the body may need to be encode (see `?POST`)

For this type of question, you should go to https://community.rstudio.com. This is a Q&A site where the audience is broader, and it is dedicated to question. The github issues are prefered for Feature Request and Issues with the 📦

**Comment by picousse** [comment]
I'm aware that my example sucks. The api is an in company api, not public, which makes a reprex rather difficult.
I have an url and i have the json object for the query (q_object). in curl I have to dump the latter in postfields. And then it works. query_base is a simple url.

Thanks for the help. I originally thought I bumped into a bug of the package, but I discovered yesterday that one of loaded packages had overwritten the config of httr. At least that is what I think. I couldn't see anything form inside GET(config()) in the verbose somehow.
That is the reason why I posted overhere. I'll hed over to the community then...

**Comment by cderv** [comment]
Did you try the `POST` command ? 
I mixed up earlier on your variable name
```r
res <- POST(query_base, 
    # pass your query in the body of the POST. 
    body = q_object, 
    # add header 'Content-Type: application/json'
    content_type_json(), 
    # add basic auth header
    authenticate(config_ib$slims$username, config_ib$slims$password, type="basic")
status_code(res)
````
When you'll move to community, you can put the link here and close this issue then.

**Comment by picousse** [comment]
Hi,
No luck :-(
I tried a bit of everything, including the POST command. Still get a 400 whilst that same q_object works with the curl R package.
I'll see whether i give up or move to the community thing.
