### ISSUE TITLE
Warning when downloading from FTP

### ISSUE THREAD

**Issue by billdenney** [r-lib/httr#537]
When downloading from FTP, no http status should be expected (or maybe one should be imputed based on the results of the download), but there is a warning when trying to parse it:

``` r
> GET("ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/DVS/natality/Nat2015ps.zip")
Warning in parse_http_status(lines[[1]]) :
  NAs introduced by coercion to integer range
Warning: Failed to parse headers:
229 Entering Extended Passive Mode (|||64946|)
213 1255090
125 Data connection already open; Transfer starting.
226 Transfer complete.

Response [ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/DVS/natality/Nat2015ps.zip]
  Date: 2018-09-07 16:45
  Status: 226
  Content-Type: <unknown>
  Size: 1.26 MB
<BINARY BODY>
> 
```

**Comment by cderv** [comment]
I think it is because httr :package: is [not made to support](https://github.com/r-lib/httr/issues/190#issuecomment-98742965) ftp. However no warning or error is thrown to inform about that.

To download from ftp, I would rely directly on `curl`
```
res <- curl::curl_download("ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/DVS/natality/Nat2015ps.zip", destfile = tempfile())
```

**Comment by billdenney** [comment]
Could a more informative warning be provided then like: “httr does not parse headers unless the transport is http or https.”?  And in cases other than http/https, make no attempt to parse the header, since it's unsupported.

**Comment by hadley** [comment]
There's no support for ftp in httr. A more informative error message is not high priority because I don't think this is a common source of confusion because httr is clearly branded around http. (But I'd happily review a PR if one was provided)
