### ISSUE TITLE
POST could take toJSON parameters

### ISSUE THREAD

**Issue by viddagrava** [r-lib/httr#539]
If `encoding="json"`, it would be really helpful if `jsonlite::toJSON` parameters could be provided to the `POST` function (or also in the other request types).

Right now only `auto_unbox = TRUE` is applied, however, it could be quite flexible if we could provide the rest of the parameters as well.

I have a use case where I have to send geo-coordinates to an API within a json object. In order to overcome the `digits=4` default parameter of `toJSON`, I have to manually encode my object and send the request as `"raw"`. This is my current workaround.

Any feedback?

**Comment by shrektan** [comment]
I'm looking for the answer, too. After some searching, this, https://github.com/r-lib/httr/pull/364 and https://github.com/r-lib/httr/issues/455 , I decide to use raw as the workaround...

**Comment by hadley** [comment]
I don't think there's any way to make this work with the current httr API, but it's definitely something we'll think about in httr2.  For now, as @shrektan suggests, just convert to json yourself
