### ISSUE TITLE
Encoding special characters using 'query'

### ISSUE THREAD

**Issue by swood-ecology** [r-lib/httr#540]
I'm having a hard time encoding special characters using the 'query' parameter with GET. The following works:

```
GET("http://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent?aoi=01047&startdate=1/1/1998&enddate=12/31/2017&statisticsType=1")
```

However, this does not work:
```
url <- "http://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent"
x <- GET(url,query=list(aoi="01047",
                   startdate="1/1/1998",
                   enddate="12/31/2017",
                   statisticsTypes="1"))
```

If I look at the content of 'x', I get a query with the following format:
```[http://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent?aoi=01047&startdate=1%2F1%2F1998&enddate=12%2F31%2F2017&statisticsTypes=1]```

Notice that the date code is not in the format that I specified in the query parameter. The GET() function seems to do fine with that format when I just pass a single url, but doesn't do well with a url followed by the query parameter. Any ideas what might be going on?

**Comment by cderv** [comment]
`query` parameter are escaped for url encoding. It seems that your API don't expect url encoded request.
To prevent escaping of query parameter, youcan use `I(...)` around you value. 
Something like that should work 
``` r
url <- "http://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent"
# Escaped query
httr::modify_url(url, query = list(
  aoi = "01047",
  startdate = "1/1/1998",
  enddate = "12/31/2017",
  statisticsTypes = "1"
))
#> [1] "http://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent?aoi=01047&startdate=1%2F1%2F1998&enddate=12%2F31%2F2017&statisticsTypes=1"
# does not escape date
httr::modify_url(url, query = list(
  aoi = "01047",
  startdate = I("1/1/1998"),
  enddate = I("12/31/2017"),
  statisticsTypes = "1"
))
#> [1] "http://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent?aoi=01047&startdate=1/1/1998&enddate=12/31/2017&statisticsTypes=1"
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment]
Thanks @cderv!
