### ISSUE TITLE
Combining write_disk() and http errors

### ISSUE THREAD

**Issue by peterdesmet** [r-lib/httr#553]
Is there a way to use `write_disk()` in combination with checking for http errors? I.e. to prevent writing anything to disk on a 404 error? It seems `write_disk()` will be invoked no matter what the http status.

E.g. https://lw-enram.s3-eu-west-1.amazonaws.com/be/jab/2016/bejab201611.zip returns a 404 **and** some content in the body (a message indicating the file is not found).

```R
library(httr)
url <- "https://lw-enram.s3-eu-west-1.amazonaws.com/be/jab/2016/bejab201611.zip" # 404
download_path <- "tmp.zip"

response <- GET(url, write_disk(download_path, overwrite = TRUE))
```

Will write a `tmp.zip` file to desk with the response body information:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>be/jab/2016/bejab201611.zip</Key>
<RequestId>120F0C9F1749189D</RequestId>
<HostId>
MXu1aDXsNGINb6Jvee67eUt3dbEQZ0da9N7ONocnF/kLopztuVqRv5aFOelvJvt8WDqWJvlvzNQ=
</HostId>
</Error>
```

Is the only way to avoid this removing the file afterwards?

```R
library(httr)
url <- "https://lw-enram.s3-eu-west-1.amazonaws.com/be/jab/2016/bejab201611.zip" # 404
download_path <- "tmp.zip"

response <- GET(url, write_disk(download_path, overwrite = TRUE))
warn_for_status(response, paste("find data at", url))
if (http_error(response) && file.exists(download_path)) {
  file.remove(download_path)
}
```

**Comment by hadley** [comment]
Yeah, unfortunately that's the only way. The `write_disk()` receives the body as it comes it; no header parsing has occurred at that point.
