### ISSUE TITLE
Example for service-account.json

### ISSUE THREAD

**Issue by randyzwitch** [r-lib/httr#559]
For the service account example, you have the following code:

https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/demo/service-account.R#L15

It would be super helpful to have either an example file/vignette or helper function to generate what is actually in the `"demo/service-account.json"` file (it appears that these downloaded files might be Google specific?)

**Comment by hadley** [comment]
You have to download them from google.

**Comment by randyzwitch** [comment]
What about APIs that aren't Google APIs?

**Comment by hadley** [comment]
You're on your own, unfortunately. I don't think many other providers have service accounts.
