### ISSUE TITLE
Submitting an explicitly NULL parameter via httr

### ISSUE THREAD

**Issue by peterhurford** [r-lib/httr#561]
Is there a way to submit NULL as a JSON parameter via httr?

When I do `httr::POST("https://httpbin.org/post", body = list(a = 1, b = NULL), httr::verbose(), encode = "json”)`, I see in the output that `b = NULL` gets dropped from the payload somewhere, even though `list(a = 1, b = NULL)` is a valid R list that has an existent b value set to `NULL`.

In Python's requests library, submitting a None parameter is permitted and I'm using an API that depends on that behavior (maybe not the smartest design choice, but it's what I have to live with). Is there any way for `httr` or `RCurl` or something to interface with this?

**Comment by cderv** [comment]
here are some ways to make it works

You can use a raw body for that

``` r
httr::POST("https://httpbin.org/post", body = '{"a":1,"b":{}}', encode = "raw")
#> Response [https://httpbin.org/post]
#>   Date: 2019-01-03 20:53
#>   Status: 200
#>   Content-Type: application/json
#>   Size: 464 B
#> {
#>   "args": {}, 
#>   "data": "{\"a\":1,\"b\":{}}", 
#>   "files": {}, 
#>   "form": {}, 
#>   "headers": {
#>     "Accept": "application/json, text/xml, application/xml, */*", 
#>     "Accept-Encoding": "gzip, deflate", 
#>     "Connection": "close", 
#>     "Content-Length": "14", 
#> ...
```

or build the body directly using `jsonlite`

``` r
json_body <- jsonlite::toJSON(list(a = 1, b = NULL), auto_unbox = TRUE)
httr::POST("https://httpbin.org/post", body = json_body, encode = "raw")
#> Response [https://httpbin.org/post]
#>   Date: 2019-01-03 20:53
#>   Status: 200
#>   Content-Type: application/json
#>   Size: 464 B
#> {
#>   "args": {}, 
#>   "data": "{\"a\":1,\"b\":{}}", 
#>   "files": {}, 
#>   "form": {}, 
#>   "headers": {
#>     "Accept": "application/json, text/xml, application/xml, */*", 
#>     "Accept-Encoding": "gzip, deflate", 
#>     "Connection": "close", 
#>     "Content-Length": "14", 
#> ...
```

<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

In fact, it think it is how httr work because if `body` is a list, 
https://github.com/r-lib/httr/blob/307c7df53cd6cb3512764b9e605c1f955587019a/R/body.R#L50
So any `NULL` element in `body` will be remove. 

Does one of the two previous solutions seems ok to you ?

**Comment by peterhurford** [comment]
Thanks @cderv, that's very helpful :+1:

**Comment by msberends** [comment]
Late to the game, but although the provided answer by @cderv is nice, it does not work for e.g. the Microsoft Graph API where `null` has to be defined explicitly (which is not the same as leaving out a value [as explained here](https://stackoverflow.com/a/21121267/4575331)).

For those cases, you can use the `null` argument of `jsonlite::toJSON()`:

```r
json_body <- jsonlite::toJSON(list(a = 1, b = NULL), auto_unbox = TRUE, null = "null")
json_body
#> {"a":1,"b":null}
```

Many thanks for the `httr` package, it's truly awesome!
