### ISSUE TITLE
httr equivalent to curl::has_internet

### ISSUE THREAD

**Issue by boshek** [r-lib/httr#562]
Such an amazing and comprehensive package that really does almost everything. Thank you for developing this. 

One thing - currently (AFAIK) httr does not offer any functions that check if the user actually has access to the internet; checking for the internet is not part of a httr workflow. This is potentially problematic as 492 packages on CRAN import on httr and it seems likely that many of them are not following this recent revision to the [CRAN policies](https://cran.r-project.org/web/packages/policies.html):

> Packages which use Internet resources should fail gracefully with an informative message if the resource is not available (and not give a check warning nor error).

The best way that I know to currently meet the above CRAN requirement is with `curl::has_internet()`. I am curious, if you would consider re-exporting that function or provide similar functionality in another way? 

I realize that curl is already imported by httr but I think explicitly including a function like this would provide a useful component of the general httr workflow.

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
