### ISSUE TITLE
OAuth 2.0 resource owner authentication

### ISSUE THREAD

**Issue by hongooi73** [r-lib/httr#564]
(As opposed to http basic authentication, which is what `authenticate` does.)

Does httr support this? This is authenticating via a username and password, as opposed to a client secret:

https://tools.ietf.org/html/rfc6749#section-4.3.2

```
4.3.2.  Access Token Request

   The client makes a request to the token endpoint by adding the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body:

   grant_type
         REQUIRED.  Value MUST be set to "password".

   username
         REQUIRED.  The resource owner username.

   password
         REQUIRED.  The resource owner password.

   scope
         OPTIONAL.  The scope of the access request as described by
         Section 3.3.

   If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1.

   For example, the client makes the following HTTP request using
   transport-layer security (with extra line breaks for display purposes
   only):

     POST /token HTTP/1.1
     Host: server.example.com
     Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
     Content-Type: application/x-www-form-urlencoded

     grant_type=password&username=johndoe&password=A3ddj3w
```

**Comment by cderv** [comment]
There is a `use_basic_auth` argument in `oauth2_*` function. This passes the `key` and `secret` from the app as basic authentication. Did you try ? 

What you linked to is specific to _Resource Owner Password Credentials Grant_ and may need a `grand_type=password` to work. So, I am not sure there is already a full integration with that but is possible by also using `user_params=` to customize the request.

Do you have an API in mind so that this could be tested further ? it would help to have an example of such an api. thanks!

**Comment by Hong-Revo** [comment]
Yes, the `use_basic_auth` arg refers to http basic authentication via `authenticate()`.

**Comment by cderv** [comment]
Ok, so if you tried, with which API ? 
I can't help if you can't provide something to test with. I don't have this kind of API at hand. Thank you.

**Comment by Hong-Revo** [comment]
By the cunning stratagem of reading the source, I have determined that httr does not support this.

**Comment by cderv** [comment]
So this is a feature request. 

I really thing that already all the tools are there to make it work, and there is not so much to do to support this grant. 

However, I don't have example to test to see how an API of this type respond. You can either work on something for a PR or provide enough elements for us to see what could be done. 

Thanks.

**Comment by cderv** [comment]
From the code you linked too, there is a function to wrap the `POST` call I showed above. I believe this ok for you so nothing to do here. 

For reference, the example API is Azure which have several auth mechanisms, including [resource owner grant type](https://blogs.msdn.microsoft.com/wushuai/2016/09/25/resource-owner-password-credentials-grant-in-azure-ad-oauth/)

**Comment by hadley** [comment]
Implemented in httr2: https://httr2.r-lib.org/reference/req_oauth_password.html
