### ISSUE TITLE
Documentation of authenticate() is confusing

### ISSUE THREAD

**Issue by rolweber** [r-lib/httr#565]
I'm enhancing some code that is already using httr. I need to send one request with basic auth, while other requests before and after should remain unaffected. AIUI, `authenticate()` is the means to do basic auth. Its documentation says:

[_It's not obvious how to turn authentication off after using it, so I recommend using custom handles with authentication._](https://github.com/r-lib/httr/blob/master/R/authenticate.r#L3-L4)

That sounds as if enabling basic auth is a permanent setting that will affect subsequent requests. But the implementation of `authenticate()` calls `config()`, and in the respective file I read:

[_Unlike Curl (and RCurl), all configuration options are per request, not per handle._](https://github.com/r-lib/httr/blob/master/R/config.r#L11-L12)

That seems to contradict the above. Could it be that some design change was not fully reflected in the documentation of `authenticate()`? Unfortunately, I'm not firm enough with R to simply read up in the code what is actually happening.

**Comment by hadley** [comment]
I don't remember the full details, but I think `authenticate()` may be the exception to the rule.
