### ISSUE TITLE
Improve documentation on handling .httr-oauth files

### ISSUE THREAD

**Issue by meisterluk** [r-lib/httr#575]
I am not sure, whether I am too stupid for this or the documentation is insufficient, but I fail to handle ``.httr-oauth`` files properly. Thus, I am opening a documentation issue.

**Background:** I have a client using httr logins to send emails via gmailR (thanks for your work!). In general, it works just fine, but whenever he changes the password of his gmail account, he needs to update ``.httr-oauth`` files and the mess begins. His scripts employing gmailR are distributed among various folders and all of them need to contain an appropriate ``.httr-oauth`` file. My access to the infrastructure is limited to supervision sessions and thus, I cannot test the technical details much, but I think I read the documentation properly.

**Setting:** To the best of my understanding, the first connection of ``gmailR`` asks for a token by a one-time login via the web browser. One manual invocation of this process is achieved by
```
library(gmailr)
library(httr)
options(httr_oauth_cache = TRUE, httr_oob_default = TRUE)
gmail_auth()
```
Then some ``.httr-oauth`` file is created that will be read for successive connections. Now, since my client starts his R scripts via Windows' task scheduler, it is necessary that this ``.httr-oauth`` file is readable from the previous session since any request to login will fail due to a lack of a terminal/webbrowser. I only see the corresponding error message in the log files.

**My issue:** To this day, I could not find out how to specify the same filepath to some ``.httr-oauth`` file for all scripts using gmailR. Documentation-wise the best, I was able to find, was [Managing secrets](https://cran.r-project.org/web/packages/httr/vignettes/secrets.html). However, there is no documentation how to specify the path of the ``.httr-oauth`` file to be used.

**My request:**
* Can you clarify how users can create ``.httr-oauth`` files? (my snippet above should be some starting point?!)
* Can you clarify which data is stored in ``.httr-oauth`` files? Do they expire? Can I move these files to any other folder without any worries? (or does it hardcode some path)
* Can you clarify whether/how users can specify the filepath of the ``.httr-oauth`` files to be used?
* Can you outline the advantages/disadvantages of using ``.httr-oauth`` files in comparison with JSON web tokens?

**Comment by hadley** [comment]
This should now be resolved via updates to gmailr and gargle — we now store the token in a central location, and it should automatically prompt you to re-auth when needed.
