### ISSUE TITLE
How do I create a URL callback function using httr?

### ISSUE THREAD

**Issue by SatoshiReport** [r-lib/httr#578]
I am trying to get my head around URL callbacks in R. I can send a call to the server's URL using httr::content(GET(..)) In my call I need to give my callback url and then listen for a response back.

How do I create my callback URL? 
How do I listen to it?

I have gone through Google and the httr pdf but I think I am getting caught up in nomenclature. Thanks for the help.

I am trying to use this service using R:
[CryptAPI](https://cryptapi.io/docs/#/Callback/callback)

I initiate the call with:
`  data <- httr::content(GET(source_url, query = list(address=address, callback = callback_url)), as = "parsed")`

But how do I listen to my callback_url?

**Comment by hadley** [comment]
httr is about making requests, not receiving them. You'll need to use some other package like httpuv to listening to incoming requests.
