### ISSUE TITLE
GET requests stop working after some time iddle

### ISSUE THREAD

**Issue by solmos** [r-lib/httr#579]
I am writing an R package around a web API. I wrote a function that uses GET() to download some data. It works fine when I first load the package but stops working after some time not using this function. It does not give me any errors, it just keeps running forever. If, after not working, I close the RStudio session, open a new session and call the function, it works again. What could be the problem?

**Comment by hadley** [comment]
I'd recommend using `verbose()` or `with_verbose()` to figure our precisely where the problem is occurring, and then asking on <https://community.rstudio.com>, where this sort of question is a better fit.
