### ISSUE TITLE
Get data frame from the request 

### ISSUE THREAD

**Issue by orlandoandradeb** [r-lib/httr#589]
Hello every one. 

I have a simple problem but I am extremely unfamiliar with sever request process. I am analyzing data generate from an app.  I used to get that data using the function:  fromJSON , from  the library "jsonlite"

we now aggregate some filters and now we have to use another library to  have access to the data using the filters. 

I have been trying to get the data using "httr" library  but  I have been trying all day with just failures. I  get a responsive objet that  I don`t have idea what it is.  

I open it in R but seems to have a lot data less the data frame that I need from the server. 
Currently I am  coding this: 

r <- GET ("url") 

Does anybody could give me some track with this ? thank you

**Comment by cderv** [comment]
Hi, 

I recommend the [quickstart](https://httr.r-lib.org/articles/quickstart.html) to get a good understanding on how to do request on API. 
Very quickly, the object you get here is a response object from the request. It contains several parts you can retrieve (header, body). To get the content that is in the body and that I think you are looking for, you need to use `httr::content()`. If json is returned by your API, it will be parsed as a list using `fromJSON` (or a data.frame if possible). You should get what you want. 

Something like

```r
library(httr)
res <- GET(url)
# check you get a 200 status code meaning no error
status_code(res)
tab <- content(res)
```

Depending on the API you working with, you may need to provide some options and arguments. 
To help you with how to use this tool, I recommend to ask questions on https://community.rstudio.com. There is a broad community ready to help. Github is more suited for issues with the 📦.

Also a [reprex](http://reprex.tidyverse.org/) is always a good idea when asking for help. It help us help you ! 

``` r
url <- "http://httpbin.org/json"
library(httr)
res <- GET(url)
status_code(res)
#> [1] 200
tab <- content(res)
str(tab, 2)
#> List of 1
#>  $ slideshow:List of 4
#>   ..$ author: chr "Yours Truly"
#>   ..$ date  : chr "date of publication"
#>   ..$ slides:List of 2
#>   ..$ title : chr "Sample Slide Show"
```

<sup>Created on 2019-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by orlandoandradeb** [comment]
Hello @cderv thank you for your answer. I have been reading the links that you  wrote. 
Im getting a better understanding of the response object.
