### ISSUE TITLE
Be proactive about serialization formats

### ISSUE THREAD

**Issue by jennybc** [r-lib/httr#591]
Currently OAuth tokens are indexed by their hash and the method calls `serialize()` without specifying the version:

https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/oauth-token.r#L104-L107

[gargle](https://github.com/r-lib/gargle) extends `httr::Token2.0` with `Gargle2.0` and its hash method calls `super$hash()`. I am seeing that OAuth tokens cached with R 3.5 are un-retrievable after upgrading to 3.6, because their hash has changed due to the change in R's default serialization version. This is not tragic, as OAuth tokens should be regarded as perishable. But it can be somewhat mystifying.

httr2 should always set the version when doing this sort of thing going forward.

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
