### ISSUE TITLE
 How to make an API request with Oauth authentication?

### ISSUE THREAD

**Issue by pedreen** [r-lib/httr#592]
Hello.
I have an API with Oauth authentication using Google accounts and I need to make request by R script. Would your package can make possible this request?

**Comment by jennybc** [comment]
httr includes a demo for Google:

https://github.com/r-lib/httr/blob/master/demo/oauth2-google.r

And there is a package [gargle](https://gargle.r-lib.org) that is built upon httr and is Google-specific. It is in the process of being released on CRAN (it is literally in the submission system as I type this). So hopefully `install.packages("gargle")` will work soon, but only `devtools::install_github("r-lib/gargle")` works at this moment.

In future, this is a better question for a venue like [RStudio Community](https://gargle.r-lib.org).
