### ISSUE TITLE
Obsolete message on missing encoding for JSON content

### ISSUE THREAD

**Issue by aoles** [r-lib/httr#596]
Hi,
when extracting the content of a `Content-Type: application/json` response into a character vector I get a message on missing encoding:

``` r
library(httr)
res <- GET("http://httpbin.org/json")
cat(content(res, as = "text"))
#> No encoding supplied: defaulting to UTF-8.
#> {
#>   "slideshow": {
#>     "author": "Yours Truly", 
#>     "date": "date of publication", 
#>     "slides": [
#>       {
#>         "title": "Wake up to WonderWidgets!", 
#>         "type": "all"
#>       }, 
#>       {
#>         "items": [
#>           "Why <em>WonderWidgets</em> are great", 
#>           "Who <em>buys</em> WonderWidgets"
#>         ], 
#>         "title": "Overview", 
#>         "type": "all"
#>       }
#>     ], 
#>     "title": "Sample Slide Show"
#>   }
#> }
```

<sup>Created on 2019-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

However, the formal definition of the standard [RFC 7158 The JavaScript Object Notation (JSON) Data Interchange Format](http://tools.ietf.org/html/rfc7158) says in [Section 8.1. Character Encoding](http://tools.ietf.org/html/rfc7158#section-8.1):

> JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  **The default
   encoding is UTF-8**, and JSON texts that are encoded in UTF-8 are
   interoperable in the sense that they will be read successfully by the
   maximum number of implementations; there are many implementations
   that cannot successfully read texts in other encodings (such as
   UTF-16 and UTF-32).

Because the standard defines UTF-8 as being the default encoding anyway the message `No encoding supplied: defaulting to UTF-8` seems rather obsolete to me. Do you think it could be disabled in case of `application/json` content? For some context, see e.g. the discussion in https://github.com/GIScience/openelevationservice/issues/18.

Looking forward to your thoughts on this.

Cheers,
Andrzej

**Comment by hadley** [comment]
You're requesting it as a text, not as a json, so httr has to give it some encoding. I don't think it's reasonable for httr to impute that information from the content-type, because that would require a bunch of work across all content types.
