### ISSUE TITLE
httr from cli

### ISSUE THREAD

**Issue by cassiel74** [r-lib/httr#597]
I played around with rStrava an developed a script which produces an RMarkdown html file with plots of performances and other stats. 
I pushed all the stuff in a git repo on a remote server of mine (hence no DE) and connected with ssh.

Running the script on the remote server ie from cli, which in turn calls httr for auth on my Strava accont, results in an auth process which never ends.

Is there any workaround to get httr working on terminal?

**Comment by hadley** [comment]
Yes, you need to use an alternative OAuth flow. Unfortunately the process differs from service to service so I can't give much general advice.
