### ISSUE TITLE
Not able to use oauth2 for linkedin on Rstudio server

### ISSUE THREAD

**Issue by enricodata** [r-lib/httr#598]
How can I make this:
https://github.com/r-lib/httr/blob/master/demo/oauth2-linkedin.r
work also on Rstudio server?

I posted the same issue here:
https://community.rstudio.com/t/oauth2-linkedin-r-not-working/32763

**Comment by hadley** [comment]
Unfortunately the details differ from service to service, so it's hard to offer general advice.
