### ISSUE TITLE
Converting python request.get call to httr version

### ISSUE THREAD

**Issue by jacobgrasmick** [r-lib/httr#602]
I have been provided a python scrip to call and pull data from an API. Here is a generalized version of the python script:

```
url2 = 'http://someurladdress'
headers = { 'Authorization' : 'Token ' + api_key, 'Content_Type' : 'application/json' }
data = {'data1' : '1', 'data2' : '2', 'data_name' : 'some_data'}
stuff = {"0": "stuff0","1":"stuff1","2":"stuff2"}

t = requests.get(url2, headers=headers, verify=False, params=stuff, data = data)
```
here, 'params' defines specific ranges (e.g. date range) and data groups. 'data' calls the specific columns (or headers) of the data to pull.

I am trying to figure out how to reproduce this  using httr in R. I have successfully connected to the API after retrieving an api_key - status_code = 200 using the following script:
```
t<-GET(url2, add_headers('Authorization' = paste('Token ', api_key$token), 'Content_Type' = 'application/json')
```

What I cannot figure out is how to call 'params' and 'data' in the R script. I've tried query, but get a return error from the API that the 'data' is not defined.

Thank you in advance for your help!

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
