### ISSUE TITLE
hmac_sha1() generates wrong HMAC

### ISSUE THREAD

**Issue by foundinblank** [r-lib/httr#605]
It looks like `hmac_sha1()` is generating the wrong HMAC. After spending a couple hours wondering why my GET requests kept returning 403, I checked the encryption using [this HMAC generator/tester tool](https://www.freeformatter.com/hmac-generator.html#ad-output) and noticed the computed HMAC was different from what I was getting with `hmac_sha1()`. 

Compared `httr::hmac_sha1()` vs `digest::hmac(algo = 'sha1')` below. The key from `hmac()` results in successful API returns on my client, while `hmac_sha1()` doesn't.

``` r
library(glue)
library(httr)
library(digest)

api_key <- '1234abcdef'
secret_key <- 'EOvNayljX8KTNGfX7IyjPtTRL7aoBmxZ'
request_param <- glue('/users&key={api_key}')

httr_signature <- httr::hmac_sha1(request_param, secret_key)
httr_signature
#> [1] "TiXHwMeow57ZcLISRh8CnuJ9upE="

digest_signature <- digest::hmac(request_param, secret_key, algo = 'sha1')
digest_signature
#> [1] "4e25c7c0c7a8c39ed970b212461f029ee27dba91"
```

<sup>Created on 2019-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by cderv** [comment]
Just to let you know that `httr::hmac_sha1` calculates the sha1 on raw strings with `openssl::sha1` returning a raw vector **then** encode in base64 the raw output.
https://github.com/r-lib/httr/blob/d7195c2afda788e80f64cab2d0277b14949a9490/R/sha1.r#L22-L28

So you'll see some differences with comparing as is. 

`openssl::base64_encode` does not return the same on a raw hash and a character hash. As you'll see below, `openssl::sha1` used in `httr::hmac_sha1` returns a hash as raw type, `digest::hmac` returns the hash as character. Encoding in base64 the former is not the same as the later. 

🤔 I am not sure what httr should do 

Here some code from my investigation
``` r
api_key <- '1234abcdef'
secret_key <- 'EOvNayljX8KTNGfX7IyjPtTRL7aoBmxZ'
request_param <- glue::glue('/users&key={api_key}')

# returns a base 64 encoded string
httr::hmac_sha1(key = secret_key, string = request_param)
#> [1] "5hgyb0bgQ2suidFmuoXEvxTFrAU="
# it internally use `openssl::sha1` on Raw input
openssl::base64_encode(openssl::sha1(charToRaw(request_param), key = charToRaw(secret_key)))
#> [1] "5hgyb0bgQ2suidFmuoXEvxTFrAU="
# with character inputs, openssl does not output the same thing so base64_encode returns differently
openssl::base64_encode(openssl::sha1(request_param, key = secret_key))
#> [1] "ZTYxODMyNmY0NmUwNDM2YjJlODlkMTY2YmE4NWM0YmYxNGM1YWMwNQ=="
## returns a character type
openssl::sha1(request_param, key = secret_key)
#> [1] "e618326f46e0436b2e89d166ba85c4bf14c5ac05"
typeof(openssl::sha1(request_param, key = secret_key))
#> [1] "character"
## returns a raw type
openssl::sha1(charToRaw(request_param), key = charToRaw(secret_key))
#> sha1 hmac e6:18:32:6f:46:e0:43:6b:2e:89:d1:66:ba:85:c4:bf:14:c5:ac:05
typeof(openssl::sha1(charToRaw(request_param), key = charToRaw(secret_key)))
#> [1] "raw"

# digest does not have this issue, and returns character hash with both inputs (raw or character)
openssl::base64_encode(digest::hmac(secret_key, request_param, algo = 'sha1'))
#> [1] "ZTYxODMyNmY0NmUwNDM2YjJlODlkMTY2YmE4NWM0YmYxNGM1YWMwNQ=="
openssl::base64_encode(digest::hmac(charToRaw(secret_key), charToRaw(request_param), algo = 'sha1'))
#> [1] "ZTYxODMyNmY0NmUwNDM2YjJlODlkMTY2YmE4NWM0YmYxNGM1YWMwNQ=="
digest::hmac(secret_key, request_param, algo = 'sha1')
#> [1] "e618326f46e0436b2e89d166ba85c4bf14c5ac05"
digest::hmac(charToRaw(secret_key), charToRaw(request_param), algo = 'sha1')
#> [1] "e618326f46e0436b2e89d166ba85c4bf14c5ac05"

# httr::hmac_sha1 could fixed by creating a character hash from raw hash to encode a hash as character.
openssl::base64_encode(as.character(openssl::sha1(charToRaw(request_param), key = charToRaw(secret_key))))
#> [1] "ZTYxODMyNmY0NmUwNDM2YjJlODlkMTY2YmE4NWM0YmYxNGM1YWMwNQ=="
openssl::base64_encode(digest::hmac(secret_key, request_param, algo = 'sha1'))
#> [1] "ZTYxODMyNmY0NmUwNDM2YjJlODlkMTY2YmE4NWM0YmYxNGM1YWMwNQ=="
as.character(openssl::sha1(charToRaw(request_param), key = charToRaw(secret_key)))
#> [1] "e618326f46e0436b2e89d166ba85c4bf14c5ac05"
digest::hmac(secret_key, request_param, algo = 'sha1')
#> [1] "e618326f46e0436b2e89d166ba85c4bf14c5ac05"
```

<sup>Created on 2019-08-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by foundinblank** [comment]
> 🤔 I am not sure what httr should do

I guess what `httr::hmac_sha1()` should do is work with characters and return the same value as it would if someone was using other HMAC calculators on the internet, that would make sense as the expected behavior?  I've tried the top 3 calculators in a Google search and they all behave similarly to `digest::hmac(algo = `sha1`)`

**Comment by hadley** [comment]
I think if `hmac_sha1()` was wrong, it would cause a _lot_ of problems, so I'm sceptical this is the root cause of your problems.

**Comment by JimBacon** [comment]
The root cause may be that the default output from the [PHP equivalent](https://www.php.net/manual/en/function.hash-hmac.php) function, which will be used on many web servers, is incompatible. Refer to https://stackoverflow.com/questions/4522581/how-to-get-php-to-create-hmac-sha1-strings-like-objective-c

In the event that you can't change the server-side implementation, simply use digest::hmac which has the same default as PHP.
