### ISSUE TITLE
Can't figure out Withings OAuth 2.0 

### ISSUE THREAD

**Issue by TroyHernandez** [r-lib/httr#609]
OAuth 1.0 is available as an example, but is no longer supported by Withings.  Hoping that someone may have gotten 2.0 figured out, but hasn't posted it.

**Comment by cderv** [comment]
You could be interesting in this package 
https://github.com/mathesong/rwithings

It contains a working example of using Oauth2 API to connect. 

If you manage to connect, do no hesitate to PR a new demo for Oauth2 with withings.
