### ISSUE TITLE
HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by yasineahmed** [r-lib/httr#616]
POST request with size >102 KB would result in an HTTP/1.1 500 Internal Server Error.
Is there a work around for this? (Request works fine in Powershell) 

x <- POST(url=url,
          body=body,
          encode = "json",
          verbose()
) 
<- HTTP/1.1 500 Internal Server Error
<- Cache-Control: private
<- Content-Type: application/json; charset=utf-8
<- Server: Microsoft-IIS/8.5
<- jsonerror: true
<- X-AspNet-Version: 4.0.30319
<- X-Powered-By: ASP.NET
<- Date: Thu, 19 Sep 2019 00:04:28 GMT
<- Content-Length: 91

**Comment by jennybc** [comment]
A 500 error is from the server side. So it's possible that the success from Powershell and failure with httr is a coincidence. Is it repeatable?

In any case, there's not nearly enough detail here for someone to figure out what's going on.

**Comment by yasineahmed** [comment]
Hello, 
Yes, I have tested it multiple times same issue. I was able to get a response back utilizing Rcurl package postForm(). 

**Session Info**
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
httr_1.4.1 
RCurl_1.95-4.12

**httr**
`x_httr <- POST(
  url = url,
  body = list(
    RegistrationKey = RegistrationKey,
    MacroFileName = MacroFileName,
    userID = userID,
    SQLStatement = SQLStatement
  ) ,
  encode = "json",
  verbose()
) `

> -> POST /AuthenticationWS/DBService.asmx/GetDataCSV HTTP/1.1

-> User-Agent: libcurl/7.64.1 r-curl/4.0 httr/1.4.1
-> Accept-Encoding: deflate, gzip
-> Cookie: webfarm=dcir-stgws1
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/json
-> Content-Length: 198
<- _HTTP/1.1 500 Internal Server Error_
<- Cache-Control: private
<- Content-Type: application/json; charset=utf-8
<- Server: Microsoft-IIS/8.5
<- jsonerror: true
<- X-AspNet-Version: 4.0.30319
<- X-Powered-By: ASP.NET
<- Date: Thu, 19 Sep 2019 15:17:46 GMT
<- Content-Length: 91
<- {"Message":"There was an error processing the request.","StackTrace":"","ExceptionType":""}

**Rcurl**

`x_Rcurl <- postForm(
  uri = url,
  RegistrationKey = RegistrationKey,
  MacroFileName = MacroFileName,
  userID = userID,
  SQLStatement = SQLStatement,
  style = "POST",
  .opts = curlOptions(verbose = TRUE),
  curl = curl
) `


Accept: */*
Content-Length: 188
Content-Type: application/x-www-form-urlencoded
 upload completely sent off: 188 out of 188 bytes
< HTTP/1.1 200 OK
< Cache-Control: private, max-age=0
< Content-Type: text/xml; charset=utf-8
< Server: Microsoft-IIS/8.5
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.

**Comment by jennybc** [comment]
In that case, `httr::with_verbose()` is very useful for exposing detail about httr's activities. You could do same with the successful call in the shell or, perhaps, via RCurl, and look for differences that may explain what you're seeing.

**Comment by yasineahmed** [comment]
I believe this may have to do with the connection time. 
Will look at other possible causes as well. 

> **x_httr$times**
     redirect    namelookup       connect   pretransfer starttransfer         total 
     0.000000      0.004327      0.007034      0.008212      0.000000      4.417904 

**x_Rcurl times**
> $total.time
[1] 2.547
$namelookup.time
[1] 0.015
$connect.time
[1] 0.015
$pretransfer.time
[1] 0.015

**Comment by jennybc** [comment]
Looking for differences in what goes out "over the wire" is probably your best bet. Sounds like your intent is the same, but the httr call is sending a different (and problematic) payload compared to the other methods.

**Comment by yasineahmed** [comment]
Issue is resolved after changing the encoding from JSON to form. 
will need to further investigate way there is a limit in request when encode set to JSON.

**Comment by yutannihilation** [comment]
The strange part of this output is that, the server responded before the client sends the actual request.

> -> User-Agent: libcurl/7.64.1 r-curl/4.0 httr/1.4.1
> -> Accept-Encoding: deflate, gzip
> -> Cookie: webfarm=dcir-stgws1
> -> Accept: application/json, text/xml, application/xml, _/_
> -> Content-Type: application/json
> -> Content-Length: 198
> <- _HTTP/1.1 500 Internal Server Error_
> <- Cache-Control: private
> <- Content-Type: application/json; charset=utf-8
> <- Server: Microsoft-IIS/8.5
> <- jsonerror: true
> <- X-AspNet-Version: 4.0.30319
> <- X-Powered-By: ASP.NET
> <- Date: Thu, 19 Sep 2019 15:17:46 GMT
> <- Content-Length: 91
> <- {"Message":"There was an error processing the request.","StackTrace":"","ExceptionType":""}

Usually, the output should have the body like below (see `{"x":"foo"}` is included). Though I have no idea what's going on, I bet this is a bug on the server's side and not httr's fault. (Some proxy in front of the server treats the response incorrectly?)

``` 
POST(url = "https://httpbin.org/post", body = list(x = "foo") , encode = "json", verbose())
-> POST /post HTTP/1.1
-> Host: httpbin.org
-> User-Agent: libcurl/7.54.0 r-curl/4.1 httr/1.4.1
-> Accept-Encoding: deflate, gzip
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/json
-> Content-Length: 11
-> 
>> {"x":"foo"}

<- HTTP/1.1 200 OK
<- Access-Control-Allow-Credentials: true
<- Access-Control-Allow-Origin: *
<- Content-Encoding: gzip
<- Content-Type: application/json
<- Date: Fri, 20 Sep 2019 00:44:54 GMT
<- Referrer-Policy: no-referrer-when-downgrade
<- Server: nginx
<- X-Content-Type-Options: nosniff
<- X-Frame-Options: DENY
<- X-XSS-Protection: 1; mode=block
<- Content-Length: 281
<- Connection: keep-alive
<- 
Response [https://httpbin.org/post]
(snip)
```

**Comment by jennybc** [comment]
> `encode` If the body is a named list, how should it be encoded? Can be one of form (application/x-www-form-urlencoded), multipart, (multipart/form-data), or json (application/json)

Sounds like everything is working as documented. Glad you solved it.
