### ISSUE TITLE
Credentials from Pyhton

### ISSUE THREAD

**Issue by tokarskyibogdan** [r-lib/httr#624]
Is it possible to pass GA credentials I got from UI and stored in DB in JSON format to the `googleAuthR` so I can pull data from R using this credentials:
```
{
  "client_id": "XXX",
  "client_secret": "XXX",
  "refresh_token": "XXX",
  "scopes": [
    "scopes array..."
  ],
  "token": "XXX",
  "token_uri": "https://oauth2.googleapis.com/token"
}
```

**Comment by jennybc** [comment]
I would move this issue to googleAuthR.

If this is what I think it is (a user OAuth token stored as JSON), the practice of storing such a thing as JSON is semi-deprecated. So it's possible you will end up getting a recommendation to obtain/store a credential in a more conventional way, for your R work.

**Comment by MarkEdmondson1234** [comment]
> If this is what I think it is (a user OAuth token stored as JSON), the practice of storing such a thing as JSON is semi-deprecated. So it's possible you will end up getting a recommendation to obtain/store a credential in a more conventional way, for your R work.

This was the recommendation ;)

But we did find the way to build a `gargle` / `httr` token directly from this type of JSON file,  using this code borrowed from the JavaScript response of the web login library:

```r
library(httr)
the_json <- jsonlite::fromJSON("the_token.json")
gar_app <- oauth_app("google", key = the_json$client_id, secret = the_json$client_secret)
  
scope_list <- the_json$scopes

token_formatted <-
    Token2.0$new(app = gar_app,
                 endpoint = oauth_endpoints("google"),
                 credentials = list(access_token = the_json$token,
                                    refresh_token = the_json$refresh_token),
                 params = list(scope = scope_list, type = NULL,
                               use_oob = FALSE, as_header = TRUE),
                 cache_path = FALSE)
```

It avoids asking for another login.  I would still avoid it if possible though. 

This issue can be closed.
