### ISSUE TITLE
Amazon API (Login With Amazon) Issue with OAuth2 

### ISSUE THREAD

**Issue by mfpole** [r-lib/httr#627]
Hello

I feel like I am running into an issue with how "token$credentials" are being stored when using the Amazon Login with Amazon API. It is an OAuth2 process that gets an Authorization Code. 

When I run the code the token seems to generate fine but I am unable to use it as the Authorization header in my subsequent GET requests. 

Should the token R6 object have such a weird structure for credentials? I have a suspicion that the token should be found under myToken$credentials$accessToken but instead all of the information is stashed in the Name with the Value appearing empty. Here is the screenshot of my environment. 

![image](https://user-images.githubusercontent.com/5289301/68629723-da37c800-04b2-11ea-9f15-a287cc6a8c1a.png)

Let me know if what I am seeing above is expected because then I will continue troubleshooting. However, here is the process I am going through.

`appTest <- oauth_app("amazonalexa"
          ,"/my client ID/"
          ,"/my client secret/"
          ,redirect_uri = oauth_callback())

endpointTest <- oauth_endpoint(
          request = NULL
          ,authorize = "https://www.amazon.com/ap/oa"
          ,access = "https://api.amazon.com/auth/o2/token"
)

myToken <- oauth2.0_token(endpointTest
                                   ,appTest
                                   ,type  = 'application/x-www-form-urlencoded'
                                   ,cache = FALSE
                                   ,scope = "alexa::ask:skills:read"
)

GET(
    url = "https://api.amazonalexa.com/v1/skills/amzn1.ask.skill.7ae20af8-24e0-406d-9b59-b6279a72220f/metrics?startTime=2019-11-09T10:45:00Z&endTime=2019-11-10T10:45:00Z&period=SINGLE&metric=uniqueCustomers&stage=live&skillType=custom&locale=en-US"
    ,config(token = myToken)
    ,verbose()
)`

Thank you!!

**Comment by cderv** [comment]
Hello, 

I think the call to get the access token does not go well because you provide a `type` to override default behavior
```r
myToken <- oauth2.0_token(endpointTest
,appTest
,type = 'application/x-www-form-urlencoded'
,cache = FALSE
,scope = "alexa::ask:skills:read"
)
```

the help page says about `type` argument
> content type used to override incorrect server response
You are override it with a type that is not a content type so the server response is not parsed correctly and this is why you don't get the json response parse to get `myToken$credentials$accessToken`

Is there a specific reason that you provided `type` to change the default ?

**Comment by mfpole** [comment]
Ah amazing!! There wasn't a specific reason for that line (I'm fairly new to http). I removed it and it worked. Thank you for the quick response and for supporting this helpful package!
