### ISSUE TITLE
Where/how are tokens parsed? Missing refresh token from Microsoft Graph. 

### ISSUE THREAD

**Issue by keshovsharma** [r-lib/httr#631]
Sorry for an elementary question (if that's the case) - not a professional programmer by any means.

I was able to get a valid access token for the Microsoft Graph API which I have been successfully using in GET requests using httr. Below is an example:

```r
OneNote <- oauth_endpoint(
  authorize = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
  access = "https://login.microsoftonline.com/common/oauth2/v2.0/token"
)

app <- oauth_app(appname = "R_test",
                 key = "REDACTED",
                 secret = "REDACTED",
                 redirect_uri = "http://localhost:1410/")

tk <- oauth2.0_token(endpoint = OneNote,
                     app = app,
                     scope = c("Notes.ReadWrite","User.Read"),
                     use_basic_auth = FALSE,
                     user_params = list(
                       response_type = "code",
                       prompt = "select_account"
                     )
)
```

**However, this only works for an hour - then my token becomes invalid**. Removing the token and deleting *.httr-oauth*, then "singing-in" again get a new, valid access token for another hour. `tk$credentials` does not show a `refresh_token` field. However, using the calls that I have created, [I would expect that a refresh token was received](https://docs.microsoft.com/en-us/graph/auth-v2-user#get_a_token). 

**Is there any way of diagnosing what is going on?** Where can I pick apart the incoming response from Microsoft to see if one was provided? Where is the parsing of the token response found?

Any insight would be greatly appreciated!

**Comment by cderv** [comment]
Did you manage to make a custom POST request that works to refresh your token following the Microsoft doc you linked ? you may need to add some parameters to your request maybe... it mentions a `client_secret` parameter to provide in some case to the refresh token POST request.
If you have a working example, this could help to show it works with httr. 

> Is there any way of diagnosing what is going on? 

You may try to use `httr::verbose()` in your `GET` request to get some information about what is sent and received.

Hope it helps.

**Comment by keshovsharma** [comment]
Thanks so much for the response! The example code that I posted above is the working example. My credentials and custom `user_params` for using `oauth2.0_token()` produces a token object (`tk`) that has a valid access token (`tk$access_token`). However, this does not produce  a refresh token i.e. `tk$refresh_token` does not exist. Without a refresh token, I cannot produce a custom POST request. I'd be happy to do it, but basically I'd like to figure out where in the in chain of events created by `oauth2.0_token()` things are going wrong.

I definitely agree that `httr::verbose()` within the relevant requests would be very helpful. However, I can't find relevant code where `oauth2.0_token()` posts a `POST()` to Microsoft's Token Endpoint or where it receives the response back. I assume I would need to add `verbose()` at this(these) point(s) to look at that information. Could you point me in this direction?

**Comment by cderv** [comment]
> I assume I would need to add verbose() at this(these) point(s) to look at that information.

You should be able to use the `config_init` argument in `oauth2.0_token()` to pass to the POST request. something like `config_init = httr::verbose()`. 
See `?oauth2.0_token`

**Comment by keshovsharma** [comment]
Thanks so much for this input - this has helped me greatly! I used used `verbose()`, as you suggested, and I was able to view the `POST()` interaction between my program and Microsoft Graph. It looks like Microsoft is not supplying a refresh token. However, the outgoing `POST()` from httr does not conform exactly to Microsoft specifications, so this might be the issue as well. 

**Is it possible to modify the `POST()` call so that the body contains the scopes declared in `oauth2.0_token`?** Is there a quick function/argument for this? If not, could you point me to the regions of the code I should fiddle with? Basically, Microsoft expects to see these scopes in the post request to their token server but the outgoing `POST()` from httr does not contain them in my code.

**Comment by keshovsharma** [comment]
Nevermind! I spoke too soon. This is a permissions issue with my specific application. For anyone reading, in order to get a refresh token, [the application must have "offline_permissions"](https://stackoverflow.com/questions/47588820/microsoft-graph-api-not-returning-refresh-token). 

@cderv: thank you so much for you help with this!

**Comment by cderv** [comment]
Glad I could help ! 

Next time, for such question, do not hesitate to post on https://community.rstudio.com first. There is a broad community of members ready to help there. It could help identify if it is a bug or a feature request before posting in the Github issue tracker. 

Happy API request !
