### ISSUE TITLE
Mention the RETRY function in the "Best practices for API packages" vignette?

### ISSUE THREAD

**Issue by maelle** [r-lib/httr#638]
The vignette has a paragraph starting with "For many APIs, the common approach is to retry API calls that return something in the 500 range." but it doesn't mention the [`RETRY()` function](https://httr.r-lib.org/reference/RETRY.html).

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
