### ISSUE TITLE
There seems to be a problem blocking the thread when requesting.

### ISSUE THREAD

**Issue by XianglinZhang-risker** [r-lib/httr#640]
Hello, I really like httr, but when I tested it yesterday, I found that httr seems to be hung on this page after requesting the webpage, resulting in the request will always be in the request when using other languages or software. It is not clear whether it is only I have this situation, I use a POST request.

**Comment by jennybc** [comment]
Without an example someone else can run, illustrating the problem you see, this is not going to get any traction.

---

Could you please turn this into a self-contained [reprex](http://reprex.tidyverse.org/) (short for minimal **repr**oducible **ex**ample)? It will help us help you if we can be sure we're all working with/looking at the same stuff.

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

You can install reprex by running (you may already have it, though, if you have the tidyverse package installed):
```r
install.packages("reprex")
```

Thanks!
