### ISSUE TITLE
upload zip file using REST API using httr::PUT request in R

### ISSUE THREAD

**Issue by string09** [r-lib/httr#643]
I have zip file which contain folders and inside those folders - files are there. Through POSTMAN zip file gets uploaded in milliseconds. In Body for Postman - "form-data"

But same thing I am trying to execute using R programming httr::PUT request, I am getting below error :

_Error in curl::curl_fetch_memory(url, handle = handle) : transfer closed with 163 bytes remaining to read_

```r
# code
localFilePath <-
paste0(getwd(), "/TestFolder_2020-04-02 19-28.zip")

upload.response <-
httr::PUT(
URLencode(
  "https://API/UUID/Shapes"
),
add_headers(
  .headers = c("Token" = "*************",
               "Content-Type" = "application/json")
),
body = list(uploadFile = upload_file(localFilePath)),
encode = "multipart"
)
```

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
