### ISSUE TITLE
client secrets are secrets

### ISSUE THREAD

**Issue by brucehoff** [r-lib/httr#646]
I notice that the package bigrquery or one of its dependencies publishes Google OAuth client credentials for a "Tidyverse" client (the id is xyz.apps.googleusercontent.com) and traced back to this statement:

https://github.com/r-lib/httr/blob/master/vignettes/secrets.Rmd#L31

I wonder if you've considered this threat scenario:

Say someone uses the Tidyverse client credentials to generate OAuth access and refresh tokens allowing access to their Google account. Further, let's say they use those tokens in an R script and accidentally commit the credentials along with their script to a public Github repository. The access token expires in an hour so (after an hour) no one who finds it can make use of it. But the refresh token has no expiration. Anyone can take the published Tidyverse client id and secret, combine them with the refresh token, and have unlimited access to the Google account, potentially seeing their data or racking up a big compute bill for them to pay. If the client credentials were kept confidential then no one could use the exposed refresh token to generate a new access token.

The fix would be not to publish client credentials to Github but instead to direct package users to create and use their own client credentials.

**Comment by hadley** [comment]
If you publish your credentials, it's game over, no matter what. You have to reset your tokens etc anyway, so we don't think this is a realistic threat.
