### ISSUE TITLE
Add option to remove Accept from headers

### ISSUE THREAD

**Issue by SamoPP** [r-lib/httr#649]
API server I am working with rejects any request that has to many headers in the request (headers not specified in the documentation). Accept header is redundant in my specific case and API call returns status code 401 invalid request. I believe there should be a way to get rid of Accept header. Currently I do not see how I can remove Accept from headers. API I am working with specifies I can only have Content-type and Authorization. Please add a way to remove (Accept) header(s).

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
