### ISSUE TITLE
Querying multiple conditions for a single parameter with GET

### ISSUE THREAD

**Issue by jpiaskowski** [r-lib/httr#652]
I am working with a database that uses this type of formatting when querying multiple conditions within one parameter:

"http://vartestdb.nkn.uidaho.edu/trial-data-json?f[0]=year_api:2014&f[1]=year_api:2015&location=Aberdeen&"

In this example, I'm interesting in gathering data from multiple years. The location is set only to reduce the number of records returned.

```r
library(httr)

base_url = "http://vartestdb.nkn.uidaho.edu/trial-data-json?"

# works as expected
test0 <- GET( base_url, query = list(location = "Aberdeen", year = "2014")

# only returns data from year 2014
test1 <- GET(base_url, query = list(location = "Aberdeen", "year" = "2014", "year" = "2015")

# gives an error
test2 <- GET(base_url, query = list(location = "Aberdeen", year = c("2014","2015")))

# returns exactly what I want
test3 <- GET("http://vartestdb.nkn.uidaho.edu/trial-data-json?f[0]=year_api:2014&f[1]=year_api:2015&location=Aberdeen&")
```

This is the error produced:

> Error in vapply(elements, encode, character(1)) : 
>  values must be length 1,
>  but FUN(X[[2]]) result is length 2

The issue appears to be originating in [compose_query()](https://github.com/r-lib/httr/blob/master/R/url-query.r). 

Is there a solution I am missing?

**Comment by dmi3kno** [comment]
Thanks for reprex! There kind of issues are better suited for StackOverflow with `r` and `httr` tags.
With `httr` you get what you ask for:
```r
library(httr)

base_url = "http://vartestdb.nkn.uidaho.edu/trial-data-json?"

# works as expected
test0 <- GET( base_url, query = list(location = "Aberdeen", 
                                     `f[0]` = "year_api:2014",
                                     `f[1]` = "year_api:2015"))
              
# returns exactly what I want
test3 <- GET("http://vartestdb.nkn.uidaho.edu/trial-data-json?f[0]=year_api:2014&f[1]=year_api:2015&location=Aberdeen&")

identical(content(test0), content(test3))
#> TRUE
```
I think you can compose the query with some useful iteration functions in `purrr`. 
Consider closing the issue.

**Comment by jpiaskowski** [comment]
Sorry, I don't need help (or yes, I would have gone to SO or other forums). I have a solution for constructing the query string. I was more thinking this might be a feature users need. Certainly, one can expect users to search on more than one condition within a single parameter. There is nothing intuitive about ``f[0]` = "year_api:2014"`. What I am less clear on is if this format is specific to this api or more widely used.

**Comment by dmi3kno** [comment]
I am afraid this is very API specific. And yes, index in parameter name is completely non-intuitive. I guess I wanted to say that there's no magic in `httr` happening behind the scenes. Parameters are translated to URL more or less at face value. And you can serve pretty much anything in R if you backtick it. Sorry if my reply sounded unfriendly, arrogant or condescending. Happy scraping!

**Comment by jpiaskowski** [comment]
Okay, thank you. I appreciate your help and your words. I'm in charge of building tools to help others access this db, so now know what I need to do!
