### ISSUE TITLE
httr::GET From localhost to localhost (or to any other site/url) is getting blocked by company firewall

### ISSUE THREAD

**Issue by ezpzlmnsqzy2** [r-lib/httr#654]
I have an R server running on localhost:3838 trying to hit a another server on localhost:3000. I'm on a corporate network and so I am specifying a proxy for my GET request, as I have done many other times in other languages/frameworks without issue.

Somehow I am getting a 403 returned by ZScaler, the service that blocks websites like Facebook, game sites, etc. Any idea why that would that be happening, and how can I prevent it with this library? It doesn't make sense to me for localhost communication to get blocked by our firewall, and I have written very similar programs in a variety of languages on our network without ever seeing this strange issue.

Hitting the same URL with the same headers works in Postman and curl, and I can even visit the url in my browser. I am fairly certain it is something related to either my R installation, RStudio, or this library. Thanks for any help

**Comment by hadley** [comment]
No idea, sorry, and apologies for taking so long to get back to you.
