### ISSUE TITLE
Documentation doesn't mention defaults for timeout

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/httr#658]
I checked the CRAN manual and a default for `timeout` is not mentioned (maybe it's 0?)

I think a mention on both `?timeout` and `?GET` (perhaps the other REST methods' pages as well) would be helpful

**Comment by jennybc** [comment]
I suspect timeout behaviour is inherited from the curl package and curl doesn't insert too many opinions, in which case it might just be libcurl defaults. I looked into this a bit recently when writing some retry logic for gargle and I feel like the landscape I found was very much governed by defaults.

**Comment by MichaelChirico** [comment]
makes sense... how about a reference to curl documentation, and I can also file an issue there? happy to file PR

**Comment by jennybc** [comment]
I doubt anyone would object to better docs. I think the problem is that it's hard to know exactly what to say, since it's all so indirect.

**Comment by MichaelChirico** [comment]
honestly your explanation there was great for me... "the princess is in another castle". might be nice to lay out more detail in httr but it would be fragile, better to leave that to upstream. will probably file tomorrow

**Comment by jennybc** [comment]
Reading this thread might give you a quick start: https://github.com/r-lib/usethis/issues/988 because I had to peel the onion there re: timeouts.
