### ISSUE TITLE
Document use of curl::form_data in POST

### ISSUE THREAD

**Issue by kent37** [r-lib/httr#667]
Since c8f7a69 fixed #430, the `body` parameter of `httr::POST` may contain form elements created with `curl::form_data`. Unfortunately this is not mentioned in the documentation for `POST`. I suggest changing the help text at
https://github.com/r-lib/httr/blob/cb4e20c9e0b38c0c020a8756db8db7a882288eaf/R/http-post.r#L22-L23
to
```
#'   For "multipart", list elements can be strings or objects created by
#'   [upload_file()] or [curl::form_data()]. For "form", elements are coerced to strings
```
to make it easier to discover this useful functionality. Thank you!

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄 (but it looks like it's already documented). Thanks for using httr!
