### ISSUE TITLE
SSL issue?

### ISSUE THREAD

**Issue by eujinn** [r-lib/httr#669]
I am trying to make a simple GET call in R and I am getting the following error. From the API documentation it says that I need to disable the ssl verification.
 _Error in curl::curl_fetch_memory(url, handle = handle) : 
  timed out before SSL handshake_ 

Tested with the following and the issue still persist.
_library(httr)
set_config(config(use_ssl=0L, ssl_verifypeer=0L, ssl_verifyhost=0L, sslversion=3))_

Please advise.

**Comment by jennybc** [comment]
I suspect you may be better off opening this in the curl repo:

https://github.com/jeroen/curl/issues

**Comment by eujinn** [comment]
But I am calling it with httr.
Any suggestion on how can I disable SSL?

**Comment by grimbough** [comment]
This worked for me:

```r
library(httr)
url <- "https://rest.ensembl.org/"

## This fails
res <- GET(url)
#> Error in curl::curl_fetch_memory(url, handle = handle): error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

## lower the security level
httr_config <- config(ssl_cipher_list = "DEFAULT@SECLEVEL=1")
res <- with_config(config = httr_config, GET(url))
res
#> Response [https://rest.ensembl.org/]
#>   Date: 2020-10-01 10:32
#>   Status: 200
#>   Content-Type: text/html; charset=utf-8
#>   Size: 31.5 kB
#> 
#> 
#> <!DOCTYPE html>
#> 
#> 
#> 
#> <html lang="en">
#> <head>
#>         <script src="/static/js/20-prettify.js"></script>
#>         <script src="/static/js/30-jquery-1.11.1.min.js"></script>
#> ...
```
