### ISSUE TITLE
Feature Request: Expose bytes publicly

### ISSUE THREAD

**Issue by slodge** [r-lib/httr#680]
We've seen the small helper method `bytes` in https://github.com/r-lib/httr/blob/cb4e20c9e0b38c0c020a8756db8db7a882288eaf/R/progress.R#L60 - it's a nice helper method to display a byte size.

Obviously it's not hard for us to copy, paste and MIT attribute this code, but (before we do) can I check whether there's any interest in adding `bytes` to the public API of httr? Happy to provide a roxygen block and maybe a few test cases as a PR

Thanks

Stuart

**Comment by hadley** [comment]
You might want to use https://github.com/r-lib/prettyunits instead 😄
