### ISSUE TITLE
progress bar immediately shows 100%

### ISSUE THREAD

**Issue by rafapereirabr** [r-lib/httr#683]
Hi all.
I use `httr` to download files in the [geobr](https://github.com/ipeaGIT/geobr) package. The issue I'm facing is that the progress bar immediately shows 100%, but the file is not downloaded yet.

Reprex.
```
library(httr)

# one of the files we use in our package
file_url <- "http://www.ipea.gov.br/geobr/data_gpkg/census_tract/2010/33_simplified.gpkg"

httr::GET(url=file_url, httr::progress(type = "down") )

```

ps. Thanks for an amazing package.

**Comment by hadley** [comment]
Unfortunately not every server sends the correct headers to allow progress bars to work.
