### ISSUE TITLE
Configure OAuth to not use refresh tokens 

### ISSUE THREAD

**Issue by kfgibson-abcellera** [r-lib/httr#686]
I am currently generating an OAuth App with the following code:

`drive_auth(email = TRUE)`
`google_app <- httr::oauth_app(
  appname = APPNAME,
  key = KEY,
  secret = SECRET
)`
`drive_auth_configure(app = google_app, api_key = API_KEY)`
`gs4_auth_configure(app = google_app, api_key = API_KEY)`

Is there a way for me to configure the app to not use refresh tokens?

**Comment by jennybc** [comment]
It feels like you're asking a question about Google auth specifically and sort of about the gargle package, not httr.

Reading between the lines, perhaps you want to ... not use token caching? If tokens aren't cached to disk, they won't be refreshed. I guess you could still see some refreshing within a single R session.
