### ISSUE TITLE
httr::parse_url cannot handle a missing protocol

### ISSUE THREAD

**Issue by colearendt** [r-lib/httr#689]
Related to #659

It seems `httr::parse_url` has a dependency on protocol that is surprising. For instance, if protocol is not defined, then everything shows up in the `$path`, where I would expect the hostname to be parsed.

``` r
packageVersion("httr")
#> [1] '1.4.2'
httr::parse_url("myserver.com/path")
#> $scheme
#> NULL
#> 
#> $hostname
#> NULL
#> 
#> $port
#> NULL
#> 
#> $path
#> [1] "myserver.com/path"
#> 
#> $query
#> NULL
#> 
#> $params
#> NULL
#> 
#> $fragment
#> NULL
#> 
#> $username
#> NULL
#> 
#> $password
#> NULL
#> 
#> attr(,"class")
#> [1] "url"
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
