### ISSUE TITLE
RapidAPI - Status 401

### ISSUE THREAD

**Issue by seb-29** [r-lib/httr#692]
Hello! 
I am trying to access a RapidAPI as follows: 

> library(httr)
url <- "https://extract-news.p.rapidapi.com/v0/article"
> queryString <- list(url = "https://www.theverge.com/2020/4/17/21224728/bill-gates-coronavirus-lies-5g-covid-19")
> response <- VERB("GET", url, addheaders(x_rapidapi_key ="my-api-key", x_rapidapi_host = "extract-news.p.rapidapi.com"), query = queryString, contenttype("application/octet-stream"))
> content(response, "text")

However, I get the following error message: 
> Status: 401

Could you please help me solve this issue?
Thanks a lot in advance!

**Comment by hadley** [comment]
That typically implies that something has gone wrong with your auth.
