### ISSUE TITLE
httr doesn't get the 301 error ?

### ISSUE THREAD

**Issue by ilona-grabowicz** [r-lib/httr#694]
I'm using the httr package to get the status codes of urls like this:

`status_code(GET('https://www.ikea.com/pl/pl/cat/blaty-kuchenne-33546/'))`

and for example the url https://www.ikea.com/pl/pl/cat/blaty-kuchenne-33546/ should get status 301 because it gets redirected to https://www.ikea.com/pl/pl/cat/blaty-kuchenne-laminowane-33546/ but instead it gets a status code 200. (Both of them have 200). I'm confused by this behaviour.

**Comment by hadley** [comment]
httr (and httr2 which replaces it) automatically follow redirects.
