### ISSUE TITLE
HTTR authenticate gives 401 with valid password containing £

### ISSUE THREAD

**Issue by PreetikaGupta1980** [r-lib/httr#709]
•	httr::GET(url="api", config = httr::authenticate("username", pwd,  "ntlm")) gives error 401 – Unauthorized when password contains £

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
