### ISSUE TITLE
httr POST is failing timeout

### ISSUE THREAD

**Issue by snehajosam** [r-lib/httr#718]
Unable to send httr POST request with proxy settings. 
error in curl_fetch_memory(url handle = h) timeout ..... 

i tried with other languages and got the result. 

someone please help.

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to you in httr2, I'd suggest filing an issue offer there 😄. Thanks for using httr!
