### ISSUE TITLE
Error in curl fetch memory port 443 timed out

### ISSUE THREAD

**Issue by Rom1M** [r-lib/httr#719]
Hi,
Could someone help me with the following issue:
When i run the code below, I get the error message :

Error in curl::curl_fetch_memory(url, handle = handle) :
Failed to connect to api.cryptowat.ch port 443: Timed out

Code:
install.packages('cryptowatchR')
library ('cryptowatchR')
my_url <- paste("https://api.cryptowat.ch/assets")
result <- httr::GET(my_url)

The weird thing is that I ran exactly the same code on Rstudio on my private laptop and I didn't face this issue. A colleague of mine who is using the same environment has no issue either.

Looking forward to your tips on this one,

Many thanks in advance

**Comment by hadley** [comment]
Probably either there's a proxy getting in your way or the server has blocked your IP address.
