### ISSUE TITLE
Add mime type qs::qread() to httr::content()

### ISSUE THREAD

**Issue by tsenegas** [r-lib/httr#727]
Is there an easy way to add the mime type qs::qread() to the httr::content() function ?

Let's say by adding to content-parse.R something like this: 

```
parsers$`application/octet-stream` <- function(x, encoding = NULL, type = NULL, ...) {
    need_package("qs")
    qs::qread(x)
}
```

Thanks

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. httr2 uses a different parsing mechanism with less built in magic, so this wouldn't be needed in httr2.
