### ISSUE TITLE
modify_url() cannot handle API versioning

### ISSUE THREAD

**Issue by cole-johanson** [r-lib/httr#744]
Does `modify_url()` need a `version` argument? The use of modify_url() is considered best practice per the [API Best Practices vignette](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html). However, it does not seem to be able to handle a version in its `url` argument. 

If I am missing something, perhaps this issue could be used for better `modify_url` documentation. Thanks!

``` r
# The intent: This strips the versioning
url = httr::modify_url("https://api.smartsheet.com/2.0/", path = paste0("sheets"))
url
#> [1] "https://api.smartsheet.com/sheets"

# The workaround
url = httr::modify_url("https://api.smartsheet.com/", path = paste0('2.0/',"sheets"))
url
#> [1] "https://api.smartsheet.com/2.0/sheets"
```

<sup>Created on 2023-08-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
httr has been superseded in favour of httr2, so is no longer under active development. If this problem is still important to your in httr2, I'd suggest filing an issue offer there 😄
