### ISSUE TITLE
httr 1.4.7: Option seekfunction (20167) has unknown or unsupported type

### ISSUE THREAD

**Issue by rmoff** [r-lib/httr#746]
With version 1.4.6 of httr the following code ran just fine: 

```
aws.s3::s3saveRDS(x = nyc_data,
                  object = paste0(branch,"/nyc/","nyc_permits.R"), 
                  bucket = repo_name, 
                  region="",
                  use_https=useHTTPS)
```

Since 1.4.7 it fails with 

```
Error in curl::handle_setopt(handle, .list = req$options): Option seekfunction (20167) has unknown or unsupported type.
Traceback:

1. s3saveRDS(x = df, bucket = "quickstart", object = paste0(branch, 
 .     "/weather/", "data.R"), base_url = baseurl, region = "", 
 .     use_https = FALSE)
2. put_object(file = tmp, bucket = bucket, object = object, ...)
3. s3HTTP(verb = "PUT", bucket = bucket, path = paste0("/", object), 
 .     headers = headers, request_body = file, verbose = verbose, 
 .     show_progress = show_progress, ...)
4. httr::PUT(url, H, body = httr::upload_file(request_body), query = query, 
 .     show_progress, ...)
5. request_perform(req, hu$handle$handle)
6. curl::handle_setopt(handle, .list = req$options)
```

I'm wondering if it's perhaps related to [this commit](https://github.com/r-lib/httr/commit/756505fdce003e3d3bac33691f4b3dcf5e9a4d82#diff-eeb9eccdd901fea9f32aa7e3fcb8ac636997c7e88f24f6deac27f53f2f3efbacR28)?

The code is from [this notebook](https://github.com/treeverse/lakeFS-samples/blob/main/00_notebooks/R-nyc.ipynb).

**Comment by jcrodriguez1989** [comment]
Same error here when using `googleCloudStorageR::gcs_upload` function.

**Comment by hadley** [comment]
[CURLOPT_SEEKFUNCTION](https://curl.se/libcurl/c/CURLOPT_SEEKFUNCTION.html) was added in curl 7.18.0.  curl 7.18.0 was released in January 28 2008, so you'll need to figure out why you're using a 15+ year old version of curl.

**Comment by eblondel** [comment]
The issue occurs if you don't update properly `curl` R package (to get new features introduced at  https://github.com/jeroen/curl/issues/307 - see answer provided at https://github.com/jeroen/curl/issues/315), and although you might have curl version >= 7.18.0. I got the issue with R curl 3.0.0 (although running with curl **7.84.0** - 1 year old)

**Comment by hadley** [comment]
Ah thanks for letting me know — I'll bump the version of curl that httr requires.
